import type {
  Agent,
  AgentVersion,
  ApprovalRequest,
  Run,
  RunStep,
  SpendDashboard,
  SpendGroupBy,
  SpendRange,
  SpendRow,
  Task,
  ToolGrant,
  User,
} from './types'

const now = Date.now()
const mins = (n: number) => new Date(now - n * 60_000).toISOString()
const hrs = (n: number) => new Date(now - n * 3_600_000).toISOString()
const days = (n: number) => new Date(now - n * 86_400_000).toISOString()
const future = (m: number) => new Date(now + m * 60_000).toISOString()

// ══════════════════════════════════════════════════ USERS

export const users: User[] = [
  {
    id: 'usr_ada',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    email: 'frontend@sprouter.ai',
    name: 'Ada Fernsby',
    role: 'admin',
    approval_level: 4,
    tenant_name: 'Acme Holdings',
    domain_name: 'HQ · Platform',
    team: 'Platform',
    initials: 'AF',
    avatar_tone: 'accent',
  },
  {
    id: 'usr_marcelo',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    email: 'domain@sprouter.ai',
    name: 'Marcelo Ito',
    role: 'domain_admin',
    approval_level: 3,
    tenant_name: 'Acme Holdings',
    domain_name: 'Sales · Revenue',
    team: 'Sales Operations',
    initials: 'MI',
    avatar_tone: 'info',
  },
  {
    id: 'usr_priya',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    email: 'member@sprouter.ai',
    name: 'Priya Vasan',
    role: 'member',
    approval_level: 1,
    tenant_name: 'Acme Holdings',
    domain_name: 'Support · CX',
    team: 'Customer Support',
    initials: 'PV',
    avatar_tone: 'warn',
  },
]

export const coworkers: User[] = [
  {
    id: 'usr_jules',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    email: 'jules.okafor@acme.local',
    name: 'Jules Okafor',
    role: 'domain_admin',
    approval_level: 3,
    team: 'Sales Enablement',
    initials: 'JO',
    avatar_tone: 'info',
    tenant_name: 'Acme Holdings',
    domain_name: 'Sales · Revenue',
  },
  {
    id: 'usr_sana',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    email: 'sana.raad@acme.local',
    name: 'Sana Raad',
    role: 'member',
    approval_level: 2,
    team: 'Support Leads',
    initials: 'SR',
    avatar_tone: 'warn',
    tenant_name: 'Acme Holdings',
    domain_name: 'Support · CX',
  },
  {
    id: 'usr_henrik',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    email: 'henrik.dahl@acme.local',
    name: 'Henrik Dahl',
    role: 'domain_admin',
    approval_level: 3,
    team: 'Finance',
    initials: 'HD',
    avatar_tone: 'success',
    tenant_name: 'Acme Holdings',
    domain_name: 'HQ · Finance',
  },
  {
    id: 'usr_lou',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    email: 'lou.ximenes@acme.local',
    name: 'Lou Ximenes',
    role: 'member',
    approval_level: 1,
    team: 'Growth',
    initials: 'LX',
    avatar_tone: 'danger',
    tenant_name: 'Acme Holdings',
    domain_name: 'Sales · Growth',
  },
  {
    id: 'usr_wren',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    email: 'wren.abasi@acme.local',
    name: 'Wren Abasi',
    role: 'admin',
    approval_level: 4,
    team: 'Platform · Security',
    initials: 'WA',
    avatar_tone: 'accent',
    tenant_name: 'Acme Holdings',
    domain_name: 'HQ · Platform',
  },
]

export function allUsers(): User[] {
  return [...users, ...coworkers]
}

// ══════════════════════════════════════════════════ AGENTS

export const agents: Agent[] = [
  {
    id: 'agt_lead_qualifier',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    name: 'Lead Qualifier',
    description: 'Triages inbound leads, enriches records, drafts personalised outreach.',
    status: 'active',
    owner_user_id: 'usr_marcelo',
    active_version: 'ver_lq_14',
    created_at: days(62),
    updated_at: days(2),
    owner_team: 'sales',
    version_count: 14,
    tools_granted: 8,
    tools_requiring_approval: 3,
    last_run_at: mins(4),
    runs_7d: 312,
    success_rate_7d: 0.948,
    monthly_spend_usd: 1842.6,
    monthly_spend_cap_usd: 3000,
    tone: 'accent',
    glyph: 'LQ',
  },
  {
    id: 'agt_refund_resolver',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    name: 'Refund Resolver',
    description: 'Classifies refund requests against policy and issues refunds under the approved limit.',
    status: 'active',
    owner_user_id: 'usr_priya',
    active_version: 'ver_rr_08',
    created_at: days(41),
    updated_at: days(4),
    owner_team: 'support',
    version_count: 8,
    tools_granted: 6,
    tools_requiring_approval: 2,
    last_run_at: mins(18),
    runs_7d: 186,
    success_rate_7d: 0.904,
    monthly_spend_usd: 612.8,
    monthly_spend_cap_usd: 1200,
    tone: 'warn',
    glyph: 'RR',
  },
  {
    id: 'agt_invoice_reconciler',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    name: 'Invoice Reconciler',
    description: 'Matches inbound invoices to purchase orders, flags discrepancies, posts to the ledger.',
    status: 'active',
    owner_user_id: 'usr_henrik',
    active_version: 'ver_ir_05',
    created_at: days(21),
    updated_at: days(5),
    owner_team: 'finance',
    version_count: 5,
    tools_granted: 5,
    tools_requiring_approval: 4,
    last_run_at: hrs(2),
    runs_7d: 94,
    success_rate_7d: 0.978,
    monthly_spend_usd: 318.45,
    monthly_spend_cap_usd: 800,
    tone: 'info',
    glyph: 'IR',
  },
  {
    id: 'agt_vendor_onboarder',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    name: 'Vendor Onboarder',
    description: 'Collects W-9s, validates banking details, creates vendor records across systems.',
    status: 'active',
    owner_user_id: 'usr_ada',
    active_version: 'ver_vo_03',
    created_at: days(12),
    updated_at: hrs(8),
    owner_team: 'operations',
    version_count: 3,
    tools_granted: 7,
    tools_requiring_approval: 5,
    last_run_at: hrs(6),
    runs_7d: 22,
    success_rate_7d: 0.909,
    monthly_spend_usd: 88.2,
    monthly_spend_cap_usd: 400,
    tone: 'success',
    glyph: 'VO',
  },
  {
    id: 'agt_access_provisioner',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    name: 'Access Provisioner',
    description: 'Provisions SaaS accounts on hire and deprovisions on exit based on role templates.',
    status: 'active',
    owner_user_id: 'usr_wren',
    active_version: 'ver_ap_02',
    created_at: days(7),
    updated_at: hrs(4),
    owner_team: 'admin',
    version_count: 2,
    tools_granted: 9,
    tools_requiring_approval: 6,
    last_run_at: hrs(11),
    runs_7d: 14,
    success_rate_7d: 1,
    monthly_spend_usd: 41.8,
    monthly_spend_cap_usd: 250,
    tone: 'danger',
    glyph: 'AP',
  },
  {
    id: 'agt_deal_writer',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    name: 'Deal Update Writer',
    description: 'Summarises call transcripts into CRM notes and posts updates into deal Slack channels.',
    status: 'active',
    owner_user_id: 'usr_jules',
    active_version: 'ver_du_09',
    created_at: days(33),
    updated_at: days(10),
    owner_team: 'sales',
    version_count: 9,
    tools_granted: 4,
    tools_requiring_approval: 1,
    last_run_at: mins(26),
    runs_7d: 408,
    success_rate_7d: 0.993,
    monthly_spend_usd: 521.1,
    monthly_spend_cap_usd: 1000,
    tone: 'accent',
    glyph: 'DW',
  },
  {
    id: 'agt_campaign_drafter',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    name: 'Campaign Drafter',
    description: 'Generates email sequences and landing page copy from marketing briefs.',
    status: 'draft',
    owner_user_id: 'usr_lou',
    active_version: null,
    created_at: days(4),
    updated_at: hrs(14),
    owner_team: 'growth',
    version_count: 2,
    tools_granted: 3,
    tools_requiring_approval: 3,
    last_run_at: null,
    runs_7d: 0,
    success_rate_7d: 0,
    monthly_spend_usd: 0,
    monthly_spend_cap_usd: 500,
    tone: 'info',
    glyph: 'CD',
  },
  {
    id: 'agt_kb_sync',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    name: 'Knowledge Base Sync',
    description: 'Keeps the customer-facing knowledge base in sync with internal runbooks and policy docs.',
    status: 'paused',
    owner_user_id: 'usr_wren',
    active_version: 'ver_kbs_04',
    created_at: days(55),
    updated_at: days(6),
    owner_team: 'admin',
    version_count: 4,
    tools_granted: 5,
    tools_requiring_approval: 2,
    last_run_at: days(6),
    runs_7d: 0,
    success_rate_7d: 0.971,
    monthly_spend_usd: 0,
    monthly_spend_cap_usd: 600,
    tone: 'warn',
    glyph: 'KB',
  },
  {
    id: 'agt_legacy_pricing',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    name: 'Pricing Change Bot',
    description: 'Applied pricing adjustments from spreadsheets to the product catalog.',
    status: 'archived',
    owner_user_id: 'usr_ada',
    active_version: null,
    created_at: days(88),
    updated_at: days(18),
    owner_team: 'finance',
    version_count: 6,
    tools_granted: 0,
    tools_requiring_approval: 0,
    last_run_at: days(18),
    runs_7d: 0,
    success_rate_7d: 0,
    monthly_spend_usd: 0,
    monthly_spend_cap_usd: null,
    tone: 'danger',
    glyph: 'PC',
  },
]

// ══════════════════════════════════════════════════ AGENT VERSIONS

const defaultMemoryScope = (): AgentVersion['memory_scope_config'] => ({
  user_facts: true,
  session_only: false,
  domain_shared: true,
  retention_days: 30,
})

const defaultToolScope = (): AgentVersion['tool_scope_config'] => ({
  inherits_from_agent: true,
  overrides: [],
  denylist: [],
})

const defaultModelChain = (primary: string, fallbacks: string[]): AgentVersion['model_chain_config'] => ({
  primary,
  fallbacks,
  max_tokens: 4096,
  temperature: 0.4,
})

export const agentVersions: AgentVersion[] = [
  {
    id: 'ver_lq_14',
    agent_id: 'agt_lead_qualifier',
    version_number: 14,
    instruction_spec:
      'You are the Lead Qualifier for Acme Holdings sales.\n\nPrimary objective: score inbound leads against the ICP matrix, enrich them, and draft personalised outreach for sales to review.\n\nHard rules:\n— Never auto-send outbound email. Always draft for review.\n— Flag ambiguous ICP signals to a human rather than guessing.\n— Respect Apollo per-call cost caps.',
    memory_scope_config: { ...defaultMemoryScope(), retention_days: 60 },
    tool_scope_config: {
      inherits_from_agent: true,
      overrides: ['apollo.enrich_contact'],
      denylist: ['email.send_without_draft'],
    },
    approval_rules: [
      { id: 'rule_lq_1', when: 'tool = email.send', required_approver_level: 3, note: 'All outbound customer email requires review' },
      { id: 'rule_lq_2', when: 'tokens_out > 20000 in a single run', required_approver_level: 4, note: 'High-token runs get admin sign-off' },
    ],
    model_chain_config: defaultModelChain('gpt-5-mini', ['claude-sonnet-4-6']),
    is_active: true,
    created_by: 'usr_marcelo',
    created_at: days(3),
    activated_at: days(2),
    label: 'v14 · steady',
    notes: 'Tightened ICP scoring for mid-market. Blocked auto-send.',
  },
  {
    id: 'ver_lq_13',
    agent_id: 'agt_lead_qualifier',
    version_number: 13,
    instruction_spec: 'You are the Lead Qualifier. ...',
    memory_scope_config: defaultMemoryScope(),
    tool_scope_config: defaultToolScope(),
    approval_rules: [
      { id: 'rule_lq13_1', when: 'tool = email.send', required_approver_level: 3, note: 'outbound email' },
    ],
    model_chain_config: defaultModelChain('gpt-5-mini', []),
    is_active: false,
    created_by: 'usr_marcelo',
    created_at: days(9),
    activated_at: days(8),
    label: 'v13',
    notes: 'Increased enrichment budget.',
  },
  {
    id: 'ver_lq_15',
    agent_id: 'agt_lead_qualifier',
    version_number: 15,
    instruction_spec:
      'You are the Lead Qualifier. (Experimental: hand off to researcher agent when company is Fortune 500.)',
    memory_scope_config: { ...defaultMemoryScope(), domain_shared: false },
    tool_scope_config: {
      inherits_from_agent: true,
      overrides: ['apollo.enrich_contact', 'zoho_crm.read_contact'],
      denylist: [],
    },
    approval_rules: [
      { id: 'rule_lq15_1', when: 'tool = email.send', required_approver_level: 3, note: 'outbound email' },
      { id: 'rule_lq15_2', when: 'handoff_to = researcher', required_approver_level: 4, note: 'New handoff path' },
    ],
    model_chain_config: defaultModelChain('claude-opus-4-7', ['gpt-5-mini']),
    is_active: false,
    created_by: 'usr_ada',
    created_at: hrs(4),
    activated_at: null,
    label: 'v15 · draft',
    notes: 'Experimental handoff path. Not yet tested in canary.',
  },
  {
    id: 'ver_rr_08',
    agent_id: 'agt_refund_resolver',
    version_number: 8,
    instruction_spec:
      'You are the Refund Resolver.\n\nPrimary objective: evaluate refund requests against policy. Issue refunds under $200 without approval. Above $200, always request approval.\n\nHard rules:\n— Quote the policy clause in every decision.\n— Never refund without verifying the original charge first.',
    memory_scope_config: { ...defaultMemoryScope(), retention_days: 14 },
    tool_scope_config: defaultToolScope(),
    approval_rules: [
      { id: 'rule_rr_1', when: 'refund_amount_usd > 200', required_approver_level: 3, note: 'Financial impact exceeds auto-refund cap' },
      { id: 'rule_rr_2', when: 'customer.vip = true', required_approver_level: 3, note: 'VIP customers always get human touch' },
    ],
    model_chain_config: defaultModelChain('claude-sonnet-4-6', ['gpt-5-mini']),
    is_active: true,
    created_by: 'usr_priya',
    created_at: days(5),
    activated_at: days(4),
    label: 'v8',
    notes: 'Raised auto-limit to $200. Added policy quote to transcripts.',
  },
  {
    id: 'ver_ir_05',
    agent_id: 'agt_invoice_reconciler',
    version_number: 5,
    instruction_spec:
      'You are the Invoice Reconciler.\n\nPrimary objective: match inbound invoices to their purchase orders by vendor + line item totals. Flag any mismatch > $1 to finance.',
    memory_scope_config: defaultMemoryScope(),
    tool_scope_config: defaultToolScope(),
    approval_rules: [
      { id: 'rule_ir_1', when: 'total_mismatch_usd > 500', required_approver_level: 3, note: 'Material discrepancy — finance sign-off' },
      { id: 'rule_ir_2', when: 'vendor.new = true', required_approver_level: 3, note: 'Unknown vendor requires finance review' },
    ],
    model_chain_config: defaultModelChain('claude-sonnet-4-6', ['gpt-5-mini']),
    is_active: true,
    created_by: 'usr_henrik',
    created_at: days(6),
    activated_at: days(5),
    label: 'v5',
    notes: 'Switched to cross-referenced line-item matching.',
  },
  {
    id: 'ver_vo_03',
    agent_id: 'agt_vendor_onboarder',
    version_number: 3,
    instruction_spec: 'You are the Vendor Onboarder. Collect W-9, validate EIN, open records.',
    memory_scope_config: defaultMemoryScope(),
    tool_scope_config: defaultToolScope(),
    approval_rules: [
      { id: 'rule_vo_1', when: 'tool = brex.create_vendor', required_approver_level: 3, note: 'Finance approval for new vendor records' },
    ],
    model_chain_config: defaultModelChain('claude-sonnet-4-6', []),
    is_active: true,
    created_by: 'usr_ada',
    created_at: days(12),
    activated_at: days(11),
    label: 'v3',
  },
  {
    id: 'ver_ap_02',
    agent_id: 'agt_access_provisioner',
    version_number: 2,
    instruction_spec: 'You are the Access Provisioner. Provision/deprovision SaaS accounts from role templates.',
    memory_scope_config: { ...defaultMemoryScope(), session_only: true },
    tool_scope_config: defaultToolScope(),
    approval_rules: [
      { id: 'rule_ap_1', when: 'tool = aws.revoke_user OR tool = aws.create_user', required_approver_level: 4, note: 'Root-level AWS ops always require admin sign-off' },
      { id: 'rule_ap_2', when: 'tool = okta.create_user', required_approver_level: 4, note: 'Identity provisioning is admin-gated' },
    ],
    model_chain_config: defaultModelChain('claude-opus-4-7', ['claude-sonnet-4-6']),
    is_active: true,
    created_by: 'usr_wren',
    created_at: days(7),
    activated_at: days(7),
    label: 'v2',
  },
  {
    id: 'ver_du_09',
    agent_id: 'agt_deal_writer',
    version_number: 9,
    instruction_spec: 'You are the Deal Update Writer. Summarise calls, update CRM, post Slack updates.',
    memory_scope_config: defaultMemoryScope(),
    tool_scope_config: defaultToolScope(),
    approval_rules: [
      { id: 'rule_du_1', when: 'tool = email.send', required_approver_level: 3, note: 'Customer-facing email gated' },
    ],
    model_chain_config: defaultModelChain('gpt-5-mini', []),
    is_active: true,
    created_by: 'usr_jules',
    created_at: days(10),
    activated_at: days(10),
    label: 'v9',
    notes: 'Cut verbosity by 40%. Pushed Q&A log into attachment.',
  },
  {
    id: 'ver_kbs_04',
    agent_id: 'agt_kb_sync',
    version_number: 4,
    instruction_spec:
      'You are the Knowledge Base Sync.\n\nPrimary objective: detect divergence between internal runbooks and the customer-facing knowledge base. Propose diffs but never publish without approval.',
    memory_scope_config: { ...defaultMemoryScope(), retention_days: 90 },
    tool_scope_config: defaultToolScope(),
    approval_rules: [
      { id: 'rule_kbs_1', when: 'tool = zendesk.publish_article', required_approver_level: 3, note: 'All external publishing reviewed by support lead' },
    ],
    model_chain_config: defaultModelChain('claude-sonnet-4-6', ['gpt-5-mini']),
    is_active: true,
    created_by: 'usr_wren',
    created_at: days(7),
    activated_at: days(7),
    label: 'v4 (paused)',
    notes: 'Paused pending decision on new single source of truth.',
  },
]

// ══════════════════════════════════════════════════ TOOL GRANTS

interface GrantTemplate {
  tool_name: string
  provider: string
  category: ToolGrant['config']['category']
  mode: ToolGrant['mode']
  scope_type: ToolGrant['scope_type']
  scope_id: string
  approval_required: boolean
  config: ToolGrant['config']
}

const grantTemplates: Record<string, GrantTemplate> = {
  apollo_lead_search: {
    tool_name: 'apollo.lead_search',
    provider: 'Apollo',
    category: 'data',
    mode: 'read',
    scope_type: 'tenant',
    scope_id: 'ten_acme',
    approval_required: false,
    config: {
      provider: 'Apollo',
      category: 'data',
      rate_limit_per_day: 500,
      max_spend_per_call_usd: 0.1,
      notes: 'Search Apollo\'s B2B database. Read-only.',
    },
  },
  apollo_enrich_contact: {
    tool_name: 'apollo.enrich_contact',
    provider: 'Apollo',
    category: 'data',
    mode: 'read',
    scope_type: 'tenant',
    scope_id: 'ten_acme',
    approval_required: false,
    config: {
      provider: 'Apollo',
      category: 'data',
      rate_limit_per_day: 1000,
      max_spend_per_call_usd: 0.25,
      notes: 'Enrich a contact with company + title + seniority data. Per-call cost capped.',
    },
  },
  zoho_read_contact: {
    tool_name: 'zoho_crm.read_contact',
    provider: 'Zoho CRM',
    category: 'crm',
    mode: 'read',
    scope_type: 'tenant',
    scope_id: 'ten_acme',
    approval_required: false,
    config: {
      provider: 'Zoho CRM',
      category: 'crm',
      rate_limit_per_day: 2000,
      notes: 'Read-only across CRM contacts and deals.',
    },
  },
  zoho_create_contact: {
    tool_name: 'zoho_crm.create_contact',
    provider: 'Zoho CRM',
    category: 'crm',
    mode: 'write',
    scope_type: 'domain',
    scope_id: 'dom_sales',
    approval_required: false,
    config: {
      provider: 'Zoho CRM',
      category: 'crm',
      rate_limit_per_day: 400,
      notes: 'Creates a new CRM contact. De-duplication on email is handled by CRM.',
    },
  },
  zoho_write_deal: {
    tool_name: 'zoho_crm.write_deal',
    provider: 'Zoho CRM',
    category: 'crm',
    mode: 'read_write',
    scope_type: 'domain',
    scope_id: 'dom_sales',
    approval_required: false,
    config: {
      provider: 'Zoho CRM',
      category: 'crm',
      rate_limit_per_day: 400,
      notes: 'Deal note updates are additive. Rollback via CRM audit.',
    },
  },
  email_send: {
    tool_name: 'email.send',
    provider: 'Gmail',
    category: 'comms',
    mode: 'write',
    scope_type: 'domain',
    scope_id: 'dom_sales',
    approval_required: true,
    config: {
      provider: 'Gmail',
      category: 'comms',
      rate_limit_per_day: 150,
      notes: 'Outbound email. Send always requires approval.',
      allowed_channels: ['customer'],
    },
  },
  calendar_schedule: {
    tool_name: 'calendar.schedule',
    provider: 'Google Calendar',
    category: 'calendar',
    mode: 'write',
    scope_type: 'domain',
    scope_id: 'dom_sales',
    approval_required: false,
    config: {
      provider: 'Google Calendar',
      category: 'calendar',
      rate_limit_per_day: 200,
      notes: 'Schedules internal + customer meetings. External attendees auto-approval-gated.',
    },
  },
  llm_claude_sonnet: {
    tool_name: 'llm.claude_sonnet',
    provider: 'Anthropic',
    category: 'llm',
    mode: 'read_write',
    scope_type: 'tenant',
    scope_id: 'ten_acme',
    approval_required: false,
    config: {
      provider: 'Anthropic',
      category: 'llm',
      notes: 'Primary inference path. Governed by tenant-wide token budget.',
    },
  },
  llm_claude_haiku: {
    tool_name: 'llm.claude_haiku',
    provider: 'Anthropic',
    category: 'llm',
    mode: 'read_write',
    scope_type: 'tenant',
    scope_id: 'ten_acme',
    approval_required: false,
    config: {
      provider: 'Anthropic',
      category: 'llm',
      notes: 'Lower-cost inference for routing, classification, and short replies.',
    },
  },
  openai_chat: {
    tool_name: 'openai.chat_completion',
    provider: 'OpenAI',
    category: 'llm',
    mode: 'read_write',
    scope_type: 'tenant',
    scope_id: 'ten_acme',
    approval_required: false,
    config: {
      provider: 'OpenAI',
      category: 'llm',
      notes: 'Fallback inference path.',
    },
  },
  calendar_book_customer: {
    tool_name: 'calendar.book_customer',
    provider: 'Google Calendar',
    category: 'calendar',
    mode: 'write',
    scope_type: 'domain',
    scope_id: 'dom_sales',
    approval_required: true,
    config: {
      provider: 'Google Calendar',
      category: 'calendar',
      rate_limit_per_day: 50,
      notes: 'Any calendar event with external attendees needs approval.',
    },
  },
  stripe_refund: {
    tool_name: 'stripe.refund',
    provider: 'Stripe',
    category: 'payments',
    mode: 'write',
    scope_type: 'agent',
    scope_id: 'agt_refund_resolver',
    approval_required: true,
    config: {
      provider: 'Stripe',
      category: 'payments',
      rate_limit_per_day: 30,
      max_spend_per_call_usd: 200,
      notes: 'Auto-allowed under $200. Above cap orchestrator requests approval.',
    },
  },
  slack_post: {
    tool_name: 'slack.post_message',
    provider: 'Slack',
    category: 'comms',
    mode: 'write',
    scope_type: 'tenant',
    scope_id: 'ten_acme',
    approval_required: false,
    config: {
      provider: 'Slack',
      category: 'comms',
      rate_limit_per_day: 800,
      notes: 'Internal channels only. Customer-facing blocked via channel allowlist.',
    },
  },
  notion_create: {
    tool_name: 'notion.create_page',
    provider: 'Notion',
    category: 'docs',
    mode: 'write',
    scope_type: 'tenant',
    scope_id: 'ten_acme',
    approval_required: false,
    config: {
      provider: 'Notion',
      category: 'docs',
      rate_limit_per_day: 200,
    },
  },
  okta_user: {
    tool_name: 'okta.create_user',
    provider: 'Okta',
    category: 'infra',
    mode: 'write',
    scope_type: 'agent',
    scope_id: 'agt_access_provisioner',
    approval_required: true,
    config: {
      provider: 'Okta',
      category: 'infra',
      rate_limit_per_day: 50,
      notes: 'Always requires admin approval.',
    },
  },
  aws_revoke: {
    tool_name: 'aws.revoke_user',
    provider: 'AWS',
    category: 'infra',
    mode: 'write',
    scope_type: 'agent',
    scope_id: 'agt_access_provisioner',
    approval_required: true,
    config: {
      provider: 'AWS',
      category: 'infra',
      rate_limit_per_day: 25,
      notes: 'Root-level IAM actions admin-gated.',
    },
  },
  brex_vendor: {
    tool_name: 'brex.create_vendor',
    provider: 'Brex',
    category: 'payments',
    mode: 'write',
    scope_type: 'agent',
    scope_id: 'agt_vendor_onboarder',
    approval_required: true,
    config: {
      provider: 'Brex',
      category: 'payments',
      rate_limit_per_day: 25,
      notes: 'Vendor creation blocked until finance approves.',
    },
  },
  zendesk_publish: {
    tool_name: 'zendesk.publish_article',
    provider: 'Zendesk',
    category: 'docs',
    mode: 'write',
    scope_type: 'agent',
    scope_id: 'agt_kb_sync',
    approval_required: true,
    config: {
      provider: 'Zendesk',
      category: 'docs',
      rate_limit_per_day: 40,
      notes: 'External publishing always reviewed.',
    },
  },
}

function buildGrants(agentId: string, keys: Array<keyof typeof grantTemplates>): ToolGrant[] {
  return keys.map((k, i) => {
    const t = grantTemplates[k]
    return {
      id: `grt_${agentId}_${i}`,
      agent_id: agentId,
      tool_name: t.tool_name,
      scope_type: t.scope_type,
      scope_id: t.scope_id,
      mode: t.mode,
      approval_required: t.approval_required,
      config: t.config,
      granted: true,
      last_invoked_at: mins(5 + i * 11),
    }
  })
}

export const grantsByAgent: Record<string, ToolGrant[]> = {
  agt_lead_qualifier: buildGrants('agt_lead_qualifier', [
    'apollo_lead_search',
    'apollo_enrich_contact',
    'zoho_read_contact',
    'zoho_create_contact',
    'email_send',
    'calendar_schedule',
    'llm_claude_sonnet',
    'llm_claude_haiku',
    'slack_post',
  ]),
  agt_refund_resolver: buildGrants('agt_refund_resolver', ['zoho_read_contact', 'stripe_refund', 'email_send', 'slack_post', 'llm_claude_sonnet', 'openai_chat']),
  agt_invoice_reconciler: buildGrants('agt_invoice_reconciler', ['brex_vendor', 'slack_post', 'notion_create', 'llm_claude_sonnet', 'openai_chat']),
  agt_vendor_onboarder: buildGrants('agt_vendor_onboarder', ['brex_vendor', 'notion_create', 'email_send', 'slack_post', 'llm_claude_sonnet', 'openai_chat']),
  agt_access_provisioner: buildGrants('agt_access_provisioner', ['okta_user', 'aws_revoke', 'slack_post', 'notion_create', 'email_send', 'llm_claude_sonnet', 'openai_chat']),
  agt_deal_writer: buildGrants('agt_deal_writer', ['zoho_write_deal', 'slack_post', 'calendar_schedule', 'calendar_book_customer', 'llm_claude_sonnet']),
  agt_campaign_drafter: buildGrants('agt_campaign_drafter', ['email_send', 'notion_create', 'llm_claude_sonnet']),
  agt_kb_sync: buildGrants('agt_kb_sync', ['zendesk_publish', 'notion_create', 'slack_post', 'llm_claude_sonnet', 'openai_chat']),
  agt_legacy_pricing: [],
}

// ══════════════════════════════════════════════════ TOOL CATALOG (available tools for the Add-grant flow)

export const toolCatalog: Array<{
  key: string
  tool_name: string
  provider: string
  category: string
  default_mode: 'read' | 'write' | 'read_write'
  default_scope_type: 'tenant' | 'domain' | 'agent'
  default_scope_id: string
  default_approval_required: boolean
  description: string
  risk_hint: 'low' | 'medium' | 'high'
}> = [
  { key: 'apollo_lead_search', tool_name: 'apollo.lead_search', provider: 'Apollo', category: 'data', default_mode: 'read', default_scope_type: 'tenant', default_scope_id: 'ten_acme', default_approval_required: false, description: 'Search Apollo\'s B2B database for prospects. Read-only.', risk_hint: 'low' },
  { key: 'apollo_enrich_contact', tool_name: 'apollo.enrich_contact', provider: 'Apollo', category: 'data', default_mode: 'read', default_scope_type: 'tenant', default_scope_id: 'ten_acme', default_approval_required: false, description: 'Enrich a contact record with company + title + signals.', risk_hint: 'low' },
  { key: 'zoho_read_contact', tool_name: 'zoho_crm.read_contact', provider: 'Zoho CRM', category: 'crm', default_mode: 'read', default_scope_type: 'tenant', default_scope_id: 'ten_acme', default_approval_required: false, description: 'Read contacts, deals, activities from the CRM.', risk_hint: 'low' },
  { key: 'zoho_create_contact', tool_name: 'zoho_crm.create_contact', provider: 'Zoho CRM', category: 'crm', default_mode: 'write', default_scope_type: 'domain', default_scope_id: 'dom_sales', default_approval_required: false, description: 'Create a new CRM contact. De-duplicates on email.', risk_hint: 'medium' },
  { key: 'zoho_write_deal', tool_name: 'zoho_crm.write_deal', provider: 'Zoho CRM', category: 'crm', default_mode: 'read_write', default_scope_type: 'domain', default_scope_id: 'dom_sales', default_approval_required: false, description: 'Append notes + stage updates to a deal.', risk_hint: 'medium' },
  { key: 'email_send', tool_name: 'email.send', provider: 'Gmail', category: 'comms', default_mode: 'write', default_scope_type: 'domain', default_scope_id: 'dom_sales', default_approval_required: true, description: 'Send outbound email. Customer-facing — approval recommended.', risk_hint: 'high' },
  { key: 'calendar_schedule', tool_name: 'calendar.schedule', provider: 'Google Calendar', category: 'calendar', default_mode: 'write', default_scope_type: 'domain', default_scope_id: 'dom_sales', default_approval_required: false, description: 'Schedule internal or customer meetings.', risk_hint: 'medium' },
  { key: 'calendar_book_customer', tool_name: 'calendar.book_customer', provider: 'Google Calendar', category: 'calendar', default_mode: 'write', default_scope_type: 'domain', default_scope_id: 'dom_sales', default_approval_required: true, description: 'Book customer-facing calendar events — approval recommended.', risk_hint: 'high' },
  { key: 'llm_claude_sonnet', tool_name: 'llm.claude_sonnet', provider: 'Anthropic', category: 'llm', default_mode: 'read_write', default_scope_type: 'tenant', default_scope_id: 'ten_acme', default_approval_required: false, description: 'Primary inference path. Governed by tenant-wide token budget.', risk_hint: 'low' },
  { key: 'llm_claude_haiku', tool_name: 'llm.claude_haiku', provider: 'Anthropic', category: 'llm', default_mode: 'read_write', default_scope_type: 'tenant', default_scope_id: 'ten_acme', default_approval_required: false, description: 'Lower-cost inference for routing, classification, short replies.', risk_hint: 'low' },
  { key: 'openai_chat', tool_name: 'openai.chat_completion', provider: 'OpenAI', category: 'llm', default_mode: 'read_write', default_scope_type: 'tenant', default_scope_id: 'ten_acme', default_approval_required: false, description: 'Fallback inference path.', risk_hint: 'low' },
  { key: 'slack_post', tool_name: 'slack.post_message', provider: 'Slack', category: 'comms', default_mode: 'write', default_scope_type: 'tenant', default_scope_id: 'ten_acme', default_approval_required: false, description: 'Post to internal Slack channels. External blocked by allowlist.', risk_hint: 'medium' },
  { key: 'notion_create', tool_name: 'notion.create_page', provider: 'Notion', category: 'docs', default_mode: 'write', default_scope_type: 'tenant', default_scope_id: 'ten_acme', default_approval_required: false, description: 'Create a new Notion page in the workspace.', risk_hint: 'medium' },
  { key: 'stripe_refund', tool_name: 'stripe.refund', provider: 'Stripe', category: 'payments', default_mode: 'write', default_scope_type: 'agent', default_scope_id: 'agt_refund_resolver', default_approval_required: true, description: 'Issue refunds on live charges. Approval recommended.', risk_hint: 'high' },
  { key: 'okta_user', tool_name: 'okta.create_user', provider: 'Okta', category: 'infra', default_mode: 'write', default_scope_type: 'agent', default_scope_id: 'agt_access_provisioner', default_approval_required: true, description: 'Provision SaaS identity. Approval recommended.', risk_hint: 'high' },
]

// ══════════════════════════════════════════════════ TASKS

export const tasks: Task[] = [
  {
    id: 'tsk_4081',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    type: 'one_time',
    status: 'running',
    title: 'Refund #SR-2204 — Eliza Voss',
    user_input: 'Customer requests refund for duplicate charge on order #44021. Amount $412.',
    assigned_agent_id: 'agt_refund_resolver',
    assigned_agent_version_id: 'ver_rr_08',
    created_by: 'usr_priya',
    created_at: mins(12),
    updated_at: mins(2),
    agent_name: 'Refund Resolver',
    created_by_name: 'Priya Vasan',
    run_id: 'run_4081',
    duration_ms: 14200,
    steps_count: 7,
    spend_usd: 0.18,
    result_summary: null,
    priority: 'high',
  },
  {
    id: 'tsk_4080',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    type: 'one_time',
    status: 'running',
    title: 'Triage batch · inbound forms 10:00–11:00',
    user_input: '24 inbound form submissions. Run ICP scoring and draft outreach.',
    assigned_agent_id: 'agt_lead_qualifier',
    assigned_agent_version_id: 'ver_lq_14',
    created_by: 'usr_marcelo',
    created_at: mins(6),
    updated_at: mins(1),
    agent_name: 'Lead Qualifier',
    created_by_name: 'Marcelo Ito',
    run_id: 'run_4080',
    duration_ms: null,
    steps_count: 12,
    spend_usd: 0.84,
    result_summary: null,
    priority: 'normal',
  },
  {
    id: 'tsk_4079',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    type: 'one_time',
    status: 'completed',
    title: 'Reconcile Sep invoices · Quickbooks dump',
    user_input: 'Reconcile 38 invoices against purchase orders from August–September.',
    assigned_agent_id: 'agt_invoice_reconciler',
    assigned_agent_version_id: 'ver_ir_05',
    created_by: 'usr_henrik',
    created_at: hrs(2),
    updated_at: hrs(1),
    agent_name: 'Invoice Reconciler',
    created_by_name: 'Henrik Dahl',
    run_id: 'run_4079',
    duration_ms: 412000,
    steps_count: 56,
    spend_usd: 2.18,
    result_summary: '37 invoices matched. 1 flagged: vendor VX-012 line mismatch $148.00.',
    priority: 'normal',
  },
  {
    id: 'tsk_4078',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    type: 'chat',
    status: 'completed',
    title: 'Write Q3 deal updates for Northwind account',
    user_input: 'Summarise last 3 Northwind calls, post to #deal-northwind, update CRM notes.',
    assigned_agent_id: 'agt_deal_writer',
    assigned_agent_version_id: 'ver_du_09',
    created_by: 'usr_jules',
    created_at: hrs(3),
    updated_at: hrs(3),
    agent_name: 'Deal Update Writer',
    created_by_name: 'Jules Okafor',
    run_id: 'run_4078',
    duration_ms: 21800,
    steps_count: 9,
    spend_usd: 0.14,
    result_summary: '3 calls summarised. 1 CRM note, 1 Slack post drafted (awaiting send-approval — outbound).',
    priority: 'normal',
  },
  {
    id: 'tsk_4077',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    type: 'one_time',
    status: 'running',
    title: 'Offboard L.Chu — revoke all access',
    user_input: 'Employee ID 20184. Revoke Okta, Slack, GitHub, Notion, AWS, Stripe.',
    assigned_agent_id: 'agt_access_provisioner',
    assigned_agent_version_id: 'ver_ap_02',
    created_by: 'usr_ada',
    created_at: hrs(5),
    updated_at: hrs(4),
    agent_name: 'Access Provisioner',
    created_by_name: 'Ada Fernsby',
    run_id: 'run_4077',
    duration_ms: null,
    steps_count: 14,
    spend_usd: 0.22,
    result_summary: null,
    priority: 'urgent',
  },
  {
    id: 'tsk_4076',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    type: 'one_time',
    status: 'failed',
    title: 'Onboard Fieldston Partners LLC',
    user_input: 'Vendor W-9 attached. Validate, create records, set Net-30 terms.',
    assigned_agent_id: 'agt_vendor_onboarder',
    assigned_agent_version_id: 'ver_vo_03',
    created_by: 'usr_ada',
    created_at: hrs(6),
    updated_at: hrs(5),
    agent_name: 'Vendor Onboarder',
    created_by_name: 'Ada Fernsby',
    run_id: 'run_4076',
    duration_ms: 68000,
    steps_count: 8,
    spend_usd: 0.08,
    result_summary: 'Failed: EIN validation returned mismatch with legal name. Human review queued.',
    priority: 'normal',
  },
  {
    id: 'tsk_4075',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    type: 'schedule',
    status: 'pending',
    title: 'Re-score stalled leads · daily 06:00',
    user_input: 'Re-score leads last touched > 30 days with latest ICP criteria.',
    assigned_agent_id: 'agt_lead_qualifier',
    assigned_agent_version_id: 'ver_lq_14',
    created_by: 'usr_marcelo',
    created_at: mins(28),
    updated_at: mins(28),
    agent_name: 'Lead Qualifier',
    created_by_name: 'Marcelo Ito',
    run_id: null,
    duration_ms: null,
    steps_count: 0,
    spend_usd: 0,
    result_summary: null,
    priority: 'normal',
    schedule_cron: '0 6 * * *',
  },
  {
    id: 'tsk_4074',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    type: 'one_time',
    status: 'completed',
    title: 'Refund #SR-2201 — Tomás Grau',
    user_input: 'Customer claims product broken in transit. $89.',
    assigned_agent_id: 'agt_refund_resolver',
    assigned_agent_version_id: 'ver_rr_08',
    created_by: 'usr_priya',
    created_at: hrs(7),
    updated_at: hrs(6),
    agent_name: 'Refund Resolver',
    created_by_name: 'Priya Vasan',
    run_id: 'run_4074',
    duration_ms: 18400,
    steps_count: 5,
    spend_usd: 0.06,
    result_summary: 'Refund issued $89. No approval needed (under $200 policy).',
    priority: 'normal',
  },
  {
    id: 'tsk_4073',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    type: 'one_time',
    status: 'cancelled',
    title: 'Refund #SR-2200 — Sabine Lautner',
    user_input: 'Double-shipped item. $52.',
    assigned_agent_id: 'agt_refund_resolver',
    assigned_agent_version_id: 'ver_rr_08',
    created_by: 'usr_priya',
    created_at: hrs(8),
    updated_at: hrs(8),
    agent_name: 'Refund Resolver',
    created_by_name: 'Priya Vasan',
    run_id: 'run_4073',
    duration_ms: 4200,
    steps_count: 2,
    spend_usd: 0.01,
    result_summary: 'Cancelled by user — duplicate of #SR-2199.',
    priority: 'normal',
  },
  {
    id: 'tsk_4072',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    type: 'chat',
    status: 'running',
    title: 'Ask Deal Writer to tweak Northwind note',
    user_input: 'Can you shorten the exec summary and add the ARR delta from Q2 to Q3?',
    assigned_agent_id: 'agt_deal_writer',
    assigned_agent_version_id: 'ver_du_09',
    created_by: 'usr_jules',
    created_at: mins(42),
    updated_at: mins(2),
    agent_name: 'Deal Update Writer',
    created_by_name: 'Jules Okafor',
    run_id: null,
    duration_ms: null,
    steps_count: 3,
    spend_usd: 0.02,
    result_summary: null,
    priority: 'normal',
  },
]

// ══════════════════════════════════════════════════ RUN STEPS + RUNS

let stepCounter = 0
function mkStep(
  runId: string,
  kind: RunStep['step_type'],
  status: RunStep['status'],
  title: string,
  detail: string,
  opts: Partial<RunStep> = {}
): RunStep {
  stepCounter++
  const createdAt = opts.created_at ?? mins(30 - stepCounter)
  return {
    id: `stp_${runId}_${stepCounter.toString().padStart(3, '0')}`,
    run_id: runId,
    step_index: opts.step_index ?? stepCounter,
    step_type: kind,
    status,
    model_name: opts.model_name ?? (kind === 'llm_call' ? 'gpt-5-mini' : null),
    tool_name: opts.tool_name ?? (kind === 'tool_call' ? 'tool' : null),
    input_ref: opts.input_ref ?? `io_${stepCounter}_in`,
    output_ref: opts.output_ref ?? `io_${stepCounter}_out`,
    cost_usd: opts.cost_usd ?? (kind === 'llm_call' ? 0.01 + Math.random() * 0.04 : 0),
    tokens_in: opts.tokens_in ?? (kind === 'llm_call' ? 400 + Math.floor(Math.random() * 1200) : null),
    tokens_out: opts.tokens_out ?? (kind === 'llm_call' ? 120 + Math.floor(Math.random() * 400) : null),
    duration_ms: opts.duration_ms ?? 600 + Math.floor(Math.random() * 3000),
    created_at: createdAt,
    completed_at: status === 'pending' || status === 'running' ? null : createdAt,
    title,
    detail,
    payload: opts.payload,
    approval_id: opts.approval_id,
  }
}

function buildSteps(runId: string, builder: (mk: (kind: RunStep['step_type'], status: RunStep['status'], title: string, detail: string, opts?: Partial<RunStep>) => RunStep) => RunStep[]): RunStep[] {
  stepCounter = 0
  const local = (kind: RunStep['step_type'], status: RunStep['status'], title: string, detail: string, opts: Partial<RunStep> = {}) =>
    mkStep(runId, kind, status, title, detail, opts)
  return builder(local).map((s, idx) => ({ ...s, step_index: idx + 1 }))
}

export const runs: Record<string, Run> = {
  run_4081: {
    id: 'run_4081',
    task_id: 'tsk_4081',
    agent_version_id: 'ver_rr_08',
    status: 'suspended',
    suspended_stage: 'approval_gate · stripe.refund',
    total_cost_usd: 0.18,
    total_tokens_in: 3420,
    total_tokens_out: 810,
    error_message: null,
    started_at: mins(12),
    ended_at: null,
    agent_id: 'agt_refund_resolver',
    agent_name: 'Refund Resolver',
    version_label: 'v8',
    duration_ms: null,
    steps: buildSteps('run_4081', mk => [
      mk('llm_call', 'ok', 'Task received', 'Refund request SR-2204 · $412 · Eliza Voss', {
        model_name: 'claude-sonnet-4-6',
        payload: { order_id: '#44021', amount_usd: '412.00', customer: 'Eliza Voss', reason: 'Duplicate charge' },
      }),
      mk('memory_read', 'ok', 'Read customer facts', 'Loaded lifetime-value + prior refund history for cus_N0a2vX', {
        tool_name: 'memory.read',
        payload: { scope: 'user_facts', key: 'cus_N0a2vX', hits: '3' },
      }),
      mk('llm_call', 'ok', 'Plan drafted', '4-step plan: verify charge, check policy, request approval, notify customer', { model_name: 'claude-sonnet-4-6' }),
      mk('tool_call', 'ok', 'stripe.read_charge', 'Read charge ch_3P8fL2', {
        tool_name: 'stripe.read_charge',
        payload: { charge_id: 'ch_3P8fL2', status: 'succeeded', amount_usd: '412.00' },
      }),
      mk('validation', 'ok', 'Policy check', 'Amount $412 > $200 auto-refund cap. Rule rule_rr_1 triggered.', {
        tool_name: 'policy.check',
        payload: { rule_id: 'rule_rr_1', verdict: 'approval_required', required_approver_level: '3' },
      }),
      mk('tool_call', 'blocked', 'stripe.refund — blocked by policy', 'Tool grant requires approval above $200 cap', {
        tool_name: 'stripe.refund',
        payload: { charge_id: 'ch_3P8fL2', amount_usd: '412.00', reason: 'Customer-reported duplicate' },
      }),
      mk('approval_gate', 'pending', 'Approval requested', 'ApprovalRequest apv_9021 created; 1 approver notified', {
        approval_id: 'apv_9021',
        payload: { approver_role: 'domain_admin', approver_user_id: 'usr_marcelo', expires_in: '3h 48m' },
      }),
    ]),
  },
  run_4080: {
    id: 'run_4080',
    task_id: 'tsk_4080',
    agent_version_id: 'ver_lq_14',
    status: 'running',
    suspended_stage: null,
    total_cost_usd: 0.84,
    total_tokens_in: 18420,
    total_tokens_out: 4210,
    error_message: null,
    started_at: mins(6),
    ended_at: null,
    agent_id: 'agt_lead_qualifier',
    agent_name: 'Lead Qualifier',
    version_label: 'v14',
    duration_ms: null,
    steps: buildSteps('run_4080', mk => [
      mk('llm_call', 'ok', 'Task received', '24 inbound forms · 10:00–11:00 window', { model_name: 'gpt-5-mini' }),
      mk('llm_call', 'ok', 'Plan drafted', 'Score each · enrich via Apollo · draft outreach for top 8'),
      mk('tool_call', 'ok', 'apollo.enrich_contact × 24', 'Enrichment batch complete', {
        tool_name: 'apollo.enrich_contact',
        cost_usd: 0.24,
        duration_ms: 6400,
      }),
      mk('tool_call', 'ok', 'zoho_crm.read_contact × 24', 'De-duplication against existing CRM contacts', {
        tool_name: 'zoho_crm.read_contact',
      }),
      mk('memory_write', 'ok', 'Persist ICP scores', 'Wrote scores to user_facts memory scope', {
        tool_name: 'memory.write',
        payload: { scope: 'domain_shared', count: '17' },
      }),
      mk('llm_call', 'ok', 'Scored leads', '8 high-fit, 9 mid-fit, 7 low-fit (filtered)'),
      mk('tool_call', 'ok', 'zoho_crm.write_deal × 17', 'Posting ICP scores to deal records', {
        tool_name: 'zoho_crm.write_deal',
      }),
      mk('tool_call', 'running', 'email.send (draft × 8) — awaiting approval batch', 'Drafting personalised outreach for high-fit leads', {
        tool_name: 'email.send',
      }),
    ]),
  },
  run_4079: {
    id: 'run_4079',
    task_id: 'tsk_4079',
    agent_version_id: 'ver_ir_05',
    status: 'completed',
    suspended_stage: null,
    total_cost_usd: 2.18,
    total_tokens_in: 48200,
    total_tokens_out: 9800,
    error_message: null,
    started_at: hrs(2),
    ended_at: hrs(1),
    agent_id: 'agt_invoice_reconciler',
    agent_name: 'Invoice Reconciler',
    version_label: 'v5',
    duration_ms: 412000,
    steps: buildSteps('run_4079', mk => [
      mk('llm_call', 'ok', 'Task received', '38 invoices from Quickbooks export', { model_name: 'claude-sonnet-4-6' }),
      mk('llm_call', 'ok', 'Plan drafted', 'Match each invoice by vendor + PO + line-item totals'),
      mk('tool_call', 'ok', 'quickbooks.read_invoice × 38', 'Loaded full invoice line items', { tool_name: 'quickbooks.read_invoice' }),
      mk('tool_call', 'ok', 'quickbooks.read_po × 38', 'Loaded referenced POs', { tool_name: 'quickbooks.read_po' }),
      mk('memory_read', 'ok', 'Read vendor fact cache', 'Historical mismatches for vendor VX-012', { tool_name: 'memory.read' }),
      mk('llm_call', 'ok', 'Matching pass 1', '37 exact matches · 1 discrepancy on vendor VX-012'),
      mk('validation', 'ok', 'Variance check', 'Single discrepancy of $148 — under $500 rule_ir_1 threshold', {
        tool_name: 'policy.check',
      }),
      mk('tool_call', 'ok', 'slack.post_message', 'Posted discrepancy summary to #finance-alerts', { tool_name: 'slack.post_message' }),
      mk('memory_write', 'ok', 'Persist reconciliation', 'Stored outcome + flagged invoice for audit', { tool_name: 'memory.write' }),
      mk('llm_call', 'ok', 'Completed', '37 matched · 1 flagged · human review recommended', { model_name: 'claude-sonnet-4-6' }),
    ]),
  },
  run_4078: {
    id: 'run_4078',
    task_id: 'tsk_4078',
    agent_version_id: 'ver_du_09',
    status: 'completed',
    suspended_stage: null,
    total_cost_usd: 0.14,
    total_tokens_in: 6420,
    total_tokens_out: 1420,
    error_message: null,
    started_at: hrs(3),
    ended_at: hrs(3),
    agent_id: 'agt_deal_writer',
    agent_name: 'Deal Update Writer',
    version_label: 'v9',
    duration_ms: 21800,
    steps: buildSteps('run_4078', mk => [
      mk('llm_call', 'ok', 'Task received', 'Summarise last 3 Northwind calls'),
      mk('tool_call', 'ok', 'gong.read_transcripts', 'Loaded 3 transcripts', { tool_name: 'gong.read_transcripts' }),
      mk('llm_call', 'ok', 'Summarising', 'Distilled into 3 deal-state bullet summaries'),
      mk('tool_call', 'ok', 'zoho_crm.write_deal', 'Appended deal note to opportunity', { tool_name: 'zoho_crm.write_deal' }),
      mk('tool_call', 'ok', 'slack.post_message', 'Posted to #deal-northwind', { tool_name: 'slack.post_message' }),
      mk('llm_call', 'ok', 'Completed', 'CRM updated · Slack posted · Email drafted (awaiting send)'),
    ]),
  },
  run_4077: {
    id: 'run_4077',
    task_id: 'tsk_4077',
    agent_version_id: 'ver_ap_02',
    status: 'suspended',
    suspended_stage: 'approval_gate · aws.revoke_user',
    total_cost_usd: 0.22,
    total_tokens_in: 4820,
    total_tokens_out: 620,
    error_message: null,
    started_at: hrs(5),
    ended_at: null,
    agent_id: 'agt_access_provisioner',
    agent_name: 'Access Provisioner',
    version_label: 'v2',
    duration_ms: null,
    steps: buildSteps('run_4077', mk => [
      mk('llm_call', 'ok', 'Task received', 'Offboard employee 20184 · urgent', { model_name: 'claude-opus-4-7' }),
      mk('llm_call', 'ok', 'Plan drafted', 'Revoke in order: Stripe, AWS, GitHub, Notion, Slack, Okta'),
      mk('tool_call', 'ok', 'hris.read_employee', 'Confirmed exit date = today', { tool_name: 'hris.read_employee' }),
      mk('approval_gate', 'pending', 'Approval requested · AWS revocation', 'Root AWS access removal always requires admin approval', {
        approval_id: 'apv_9022',
        payload: { approver_role: 'admin', approver_user_id: 'usr_wren' },
      }),
      mk('llm_call', 'ok', 'Suspended', 'Pausing until admin approves scope'),
    ]),
  },
  run_4076: {
    id: 'run_4076',
    task_id: 'tsk_4076',
    agent_version_id: 'ver_vo_03',
    status: 'failed',
    suspended_stage: null,
    total_cost_usd: 0.08,
    total_tokens_in: 2840,
    total_tokens_out: 410,
    error_message: 'IRS EIN verification returned mismatch with declared legal name ("Fieldston Partners LLC" vs filed "Fieldston Holdings Partners LLC"). Escalating to human reviewer.',
    started_at: hrs(6),
    ended_at: hrs(5),
    agent_id: 'agt_vendor_onboarder',
    agent_name: 'Vendor Onboarder',
    version_label: 'v3',
    duration_ms: 68000,
    steps: buildSteps('run_4076', mk => [
      mk('llm_call', 'ok', 'Task received', 'Onboard Fieldston Partners LLC'),
      mk('tool_call', 'ok', 'docs.parse_w9', 'Extracted EIN + legal name', { tool_name: 'docs.parse_w9' }),
      mk('tool_call', 'failed', 'irs.verify_ein', 'EIN did not match legal name in IRS response', { tool_name: 'irs.verify_ein' }),
      mk('validation', 'failed', 'Run failed', 'Verification failed · escalated to human reviewer', { tool_name: 'policy.check' }),
    ]),
  },
  run_4074: {
    id: 'run_4074',
    task_id: 'tsk_4074',
    agent_version_id: 'ver_rr_08',
    status: 'completed',
    suspended_stage: null,
    total_cost_usd: 0.06,
    total_tokens_in: 2420,
    total_tokens_out: 410,
    error_message: null,
    started_at: hrs(7),
    ended_at: hrs(6),
    agent_id: 'agt_refund_resolver',
    agent_name: 'Refund Resolver',
    version_label: 'v8',
    duration_ms: 18400,
    steps: buildSteps('run_4074', mk => [
      mk('llm_call', 'ok', 'Task received', 'Refund #SR-2201 · $89 · broken in transit'),
      mk('tool_call', 'ok', 'stripe.read_charge', 'Verified original charge', { tool_name: 'stripe.read_charge' }),
      mk('validation', 'ok', 'Under policy cap', '$89 < $200 · auto-refund path', { tool_name: 'policy.check' }),
      mk('tool_call', 'ok', 'stripe.refund', 'Refund issued', { tool_name: 'stripe.refund' }),
      mk('llm_call', 'ok', 'Completed', 'Refund posted · customer notified via email draft'),
    ]),
  },
  run_4073: {
    id: 'run_4073',
    task_id: 'tsk_4073',
    agent_version_id: 'ver_rr_08',
    status: 'cancelled',
    suspended_stage: null,
    total_cost_usd: 0.01,
    total_tokens_in: 420,
    total_tokens_out: 60,
    error_message: null,
    started_at: hrs(8),
    ended_at: hrs(8),
    agent_id: 'agt_refund_resolver',
    agent_name: 'Refund Resolver',
    version_label: 'v8',
    duration_ms: 4200,
    steps: buildSteps('run_4073', mk => [
      mk('llm_call', 'ok', 'Task received', 'Refund #SR-2200'),
      mk('validation', 'skipped', 'Cancelled by user', 'Duplicate of SR-2199 · no action taken', { tool_name: 'policy.check' }),
    ]),
  },
}

// ══════════════════════════════════════════════════ APPROVALS

export const approvals: ApprovalRequest[] = [
  {
    id: 'apv_9021',
    run_id: 'run_4081',
    task_id: 'tsk_4081',
    requested_action: 'stripe.refund · $412 on charge ch_3P8fL2 (order #44021)',
    requested_by: 'usr_priya',
    requested_by_name: 'Priya Vasan',
    approver_role: 'domain_admin',
    approver_user_id: 'usr_marcelo',
    status: 'pending',
    reason: null,
    evidence_ref: 'stp_run_4081_005',
    expires_at: future(230),
    resolved_at: null,
    created_at: mins(9),
    task_title: 'Refund #SR-2204 — Eliza Voss',
    agent_id: 'agt_refund_resolver',
    agent_name: 'Refund Resolver',
    tool_name: 'stripe.refund',
    monetary_value_usd: 412,
    risk: 'medium',
    impact_scope: 'Stripe · live mode · customer cus_N0a2vX',
    policy_reason: 'Refund exceeds $200 auto-refund cap in tool grant policy.',
    payload: {
      charge_id: 'ch_3P8fL2',
      order_id: '#44021',
      amount_usd: '412.00',
      reason: 'Customer-reported duplicate charge',
      customer: 'Eliza Voss',
      customer_lifetime_value_usd: '3,840.00',
    },
    required_approver_level: 3,
  },
  {
    id: 'apv_9022',
    run_id: 'run_4077',
    task_id: 'tsk_4077',
    requested_action: 'aws.revoke_user · IAM user lchu@acme (12 attached policies)',
    requested_by: 'usr_ada',
    requested_by_name: 'Ada Fernsby',
    approver_role: 'admin',
    approver_user_id: 'usr_wren',
    status: 'pending',
    reason: null,
    evidence_ref: 'stp_run_4077_004',
    expires_at: future(120),
    resolved_at: null,
    created_at: hrs(4),
    task_title: 'Offboard L.Chu — revoke all access',
    agent_id: 'agt_access_provisioner',
    agent_name: 'Access Provisioner',
    tool_name: 'aws.revoke_user',
    monetary_value_usd: null,
    risk: 'high',
    impact_scope: 'Production AWS · us-east-1, us-west-2 · 4 running projects accessed',
    policy_reason: 'Root-level AWS permissions require admin sign-off (tenant policy).',
    payload: {
      iam_user: 'lchu@acme',
      attached_policies: '12',
      active_sessions: '0',
      last_login: '8 days ago',
    },
    required_approver_level: 4,
  },
  {
    id: 'apv_9023',
    run_id: 'run_4080',
    task_id: 'tsk_4080',
    requested_action: 'email.send batch × 8 · personalised outreach to high-fit leads',
    requested_by: 'usr_marcelo',
    requested_by_name: 'Marcelo Ito',
    approver_role: 'domain_admin',
    approver_user_id: 'usr_jules',
    status: 'pending',
    reason: null,
    evidence_ref: 'stp_run_4080_008',
    expires_at: future(360),
    resolved_at: null,
    created_at: mins(3),
    task_title: 'Triage batch · inbound forms 10:00–11:00',
    agent_id: 'agt_lead_qualifier',
    agent_name: 'Lead Qualifier',
    tool_name: 'email.send',
    monetary_value_usd: null,
    risk: 'low',
    impact_scope: 'Gmail · external recipients · 8 net-new conversations',
    policy_reason: 'All outbound customer email requires review before send.',
    payload: {
      recipients: 'high-fit leads × 8',
      sample_subject_1: 'Quick note on your request, Priya',
      sample_subject_2: 'Saw Northwind\'s latest — relevant?',
      thread_count: '8',
    },
    required_approver_level: 3,
  },
  {
    id: 'apv_9014',
    run_id: 'run_4050',
    task_id: 'tsk_4050',
    requested_action: 'stripe.refund · $280 duplicate subscription charge',
    requested_by: 'usr_priya',
    requested_by_name: 'Priya Vasan',
    approver_role: 'domain_admin',
    approver_user_id: 'usr_marcelo',
    status: 'approved',
    reason: 'Approved — loyal customer, clear double-charge in logs.',
    evidence_ref: 'stp_run_4050_005',
    expires_at: hrs(18),
    resolved_at: hrs(23),
    created_at: hrs(24),
    task_title: 'Refund #SR-2180 — Jaan Maasik',
    agent_id: 'agt_refund_resolver',
    agent_name: 'Refund Resolver',
    tool_name: 'stripe.refund',
    monetary_value_usd: 280,
    risk: 'low',
    impact_scope: 'Stripe · live mode',
    policy_reason: 'Refund exceeds $200 auto-refund cap.',
    payload: {
      charge_id: 'ch_2X8lM1',
      amount_usd: '280.00',
      reason: 'Duplicate subscription charge',
    },
    required_approver_level: 3,
  },
  {
    id: 'apv_9011',
    run_id: 'run_4030',
    task_id: 'tsk_4030',
    requested_action: 'brex.create_vendor · Taubman & Co · Net-30 ACH',
    requested_by: 'usr_ada',
    requested_by_name: 'Ada Fernsby',
    approver_role: 'domain_admin',
    approver_user_id: 'usr_henrik',
    status: 'rejected',
    reason: 'Reject — vendor already exists under different legal name.',
    evidence_ref: 'stp_run_4030_004',
    expires_at: days(1),
    resolved_at: days(2),
    created_at: days(2),
    task_title: 'Vendor onboarding — Taubman & Co',
    agent_id: 'agt_vendor_onboarder',
    agent_name: 'Vendor Onboarder',
    tool_name: 'brex.create_vendor',
    monetary_value_usd: null,
    risk: 'medium',
    impact_scope: 'Brex · vendor list',
    policy_reason: 'Finance approval required for all new vendor records.',
    payload: {
      legal_name: 'Taubman & Co',
      terms: 'Net-30',
      payment_method: 'ACH',
    },
    required_approver_level: 3,
  },
  {
    id: 'apv_9005',
    run_id: 'run_4010',
    task_id: 'tsk_4010',
    requested_action: 'okta.create_user · new hire · role template "sales_ae"',
    requested_by: 'usr_ada',
    requested_by_name: 'Ada Fernsby',
    approver_role: 'admin',
    approver_user_id: 'usr_wren',
    status: 'expired',
    reason: null,
    evidence_ref: 'stp_run_4010_003',
    expires_at: days(4),
    resolved_at: null,
    created_at: days(5),
    task_title: 'Onboard new hire · E. Mapondera',
    agent_id: 'agt_access_provisioner',
    agent_name: 'Access Provisioner',
    tool_name: 'okta.create_user',
    monetary_value_usd: null,
    risk: 'medium',
    impact_scope: 'Okta · new user · access to 11 SaaS apps',
    policy_reason: 'Identity provisioning always admin-gated.',
    payload: {
      user_email: 'e.mapondera@acme.local',
      role_template: 'sales_ae',
      manager: 'usr_jules',
    },
    required_approver_level: 4,
  },
  {
    id: 'apv_9002',
    run_id: 'run_3990',
    task_id: 'tsk_3990',
    requested_action: 'zendesk.publish_article · "Refund policy · 2026 update"',
    requested_by: 'usr_wren',
    requested_by_name: 'Wren Abasi',
    approver_role: 'domain_admin',
    approver_user_id: 'usr_marcelo',
    status: 'cancelled',
    reason: 'Cancelled by requester — superseded by updated runbook revision.',
    evidence_ref: 'stp_run_3990_006',
    expires_at: days(6),
    resolved_at: days(7),
    created_at: days(7),
    task_title: 'Sync refund policy to KB',
    agent_id: 'agt_kb_sync',
    agent_name: 'Knowledge Base Sync',
    tool_name: 'zendesk.publish_article',
    monetary_value_usd: null,
    risk: 'low',
    impact_scope: 'Zendesk · customer-facing help center',
    policy_reason: 'External publishing always reviewed by support lead.',
    payload: {
      article_id: 'kb_0184',
      diff_lines: '+42 / -18',
    },
    required_approver_level: 3,
  },
]

// ══════════════════════════════════════════════════ SPEND

function sparkSeries(base: number, trend: 'up' | 'down' | 'flat' | 'spike'): number[] {
  const out: number[] = []
  for (let i = 0; i < 14; i++) {
    let v = base
    if (trend === 'up') v = base * (0.6 + (i / 14) * 0.7)
    if (trend === 'down') v = base * (1.2 - (i / 14) * 0.7)
    if (trend === 'spike' && i === 10) v = base * 1.9
    v *= 0.85 + (Math.sin(i * 7.1 + base) * 0.5 + 0.5) * 0.35
    out.push(Math.max(0.05, v))
  }
  return out
}

function computeSpend(range: SpendRange, group_by: SpendGroupBy): SpendDashboard {
  const multiplier: Record<SpendRange, number> = { '1d': 0.03, '7d': 0.22, '30d': 1, '90d': 2.8 }
  const m = multiplier[range]
  const windowLabel: Record<SpendRange, string> = {
    '1d': 'last 24h',
    '7d': 'last 7 days',
    '30d': 'last 30 days',
    '90d': 'last 90 days',
  }
  const today = new Date().toISOString().slice(0, 10)

  const byAgentItems: SpendRow[] = agents
    .filter(a => (a.monthly_spend_usd ?? 0) > 0)
    .map(a => {
      const total = (a.monthly_spend_usd ?? 0) * m
      const tokens_in = (a.runs_7d ?? 0) * 4500 * m * 3
      const tokens_out = (a.runs_7d ?? 0) * 1200 * m * 3
      return {
        id: a.id,
        label: a.name,
        total_usd: total,
        tokens_in: Math.round(tokens_in),
        tokens_out: Math.round(tokens_out),
        run_count: Math.round((a.runs_7d ?? 0) * m * 4.2),
        spend_date: today,
        cap_usd: a.monthly_spend_cap_usd ?? null,
        trend: sparkSeries(total / 14, 'up'),
        delta_pct: 8 + (a.id.charCodeAt(4) % 18),
        kind: 'agent',
        sub_label: a.owner_team,
      }
    })

  const userAggregate: Record<string, { total: number; tokens_in: number; tokens_out: number; runs: number; label: string; sub: string }> = {}
  allUsers().forEach(u => {
    userAggregate[u.id] = {
      total: 0,
      tokens_in: 0,
      tokens_out: 0,
      runs: 0,
      label: u.name,
      sub: u.team ?? u.domain_name ?? '',
    }
  })
  agents.forEach(a => {
    const row = userAggregate[a.owner_user_id]
    if (!row) return
    row.total += (a.monthly_spend_usd ?? 0) * m
    row.tokens_in += (a.runs_7d ?? 0) * 4500 * m * 3
    row.tokens_out += (a.runs_7d ?? 0) * 1200 * m * 3
    row.runs += (a.runs_7d ?? 0) * 4.2 * m
  })
  const byUserItems: SpendRow[] = Object.entries(userAggregate)
    .filter(([, v]) => v.total > 0)
    .map(([id, v]) => ({
      id,
      label: v.label,
      total_usd: v.total,
      tokens_in: Math.round(v.tokens_in),
      tokens_out: Math.round(v.tokens_out),
      run_count: Math.round(v.runs),
      spend_date: today,
      trend: sparkSeries(v.total / 14, 'up'),
      delta_pct: 3 + (id.charCodeAt(4) % 22),
      kind: 'user',
      sub_label: v.sub,
    }))

  const items = group_by === 'agent' ? byAgentItems : byUserItems
  const total_usd = items.reduce((s, r) => s + r.total_usd, 0)

  return {
    range,
    group_by,
    total_usd,
    items: items.sort((a, b) => b.total_usd - a.total_usd),
    window_label: windowLabel[range],
    total_runs: items.reduce((s, r) => s + r.run_count, 0),
    total_spend_delta_pct: 12.4,
    total_runs_delta_pct: 22.1,
    pending_approvals: approvals.filter(a => a.status === 'pending').length,
    avg_cost_per_run_usd: items.reduce((s, r) => s + r.run_count, 0) > 0
      ? total_usd / items.reduce((s, r) => s + r.run_count, 0)
      : 0,
    burn_per_day: sparkSeries(total_usd / 17, 'up'),
    cap_usd: 6000 * m,
  }
}

export function getSpendDashboard(range: SpendRange, group_by: SpendGroupBy): SpendDashboard {
  return computeSpend(range, group_by)
}
