// All fixtures below are shaped exactly after docs/gateway.yaml schemas.
// No UI-only / denormalised fields — what you see is what the backend
// would actually return.

import type {
  Agent,
  AgentVersion,
  ApprovalRequest,
  Chat,
  ChatMessage,
  Run,
  RunStep,
  SpendDashboard,
  SpendGroupBy,
  SpendRange,
  SpendRow,
  Task,
  ToolDefinition,
  ToolGrant,
  User,
} from './types'

const now = Date.now()
const mins = (n: number) => new Date(now - n * 60_000).toISOString()
const hrs = (n: number) => new Date(now - n * 3_600_000).toISOString()
const days = (n: number) => new Date(now - n * 86_400_000).toISOString()
const future = (m: number) => new Date(now + m * 60_000).toISOString()

// ══════════════════════════════════════════════════ USERS

export const users: User[] = [
  {
    id: 'usr_ada',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    email: 'frontend@int3grate.ai',
    name: 'Ada Fernsby',
    role: 'admin',
    approval_level: 4,
    created_at: days(540),
  },
  {
    id: 'usr_marcelo',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    email: 'domain@int3grate.ai',
    name: 'Marcelo Ito',
    role: 'domain_admin',
    approval_level: 3,
    created_at: days(420),
  },
  {
    id: 'usr_priya',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    email: 'member@int3grate.ai',
    name: 'Priya Vasan',
    role: 'member',
    approval_level: 1,
    created_at: days(190),
  },
]

// ══════════════════════════════════════════════════ AGENT VERSIONS

const defaultMemoryScope = (): AgentVersion['memory_scope_config'] => ({
  user_facts: true,
  session_only: false,
  domain_shared: false,
  retention_days: 30,
})

const defaultToolScope = (): AgentVersion['tool_scope_config'] => ({
  inherits_from_agent: true,
  overrides: [],
  denylist: [],
})

const defaultModelChain = (primary: string, fallbacks: string[] = []): AgentVersion['model_chain_config'] => ({
  primary,
  fallbacks,
  max_tokens: 4096,
  temperature: 0.3,
})

export const agentVersions: AgentVersion[] = [
  {
    id: 'ver_lq_14',
    agent_id: 'agt_lead_qualifier',
    version: 14,
    instruction_spec:
      'You are a Lead Qualifier. Score inbound leads against ICP, enrich via CRM, and draft outreach for the top deciles.',
    memory_scope_config: { ...defaultMemoryScope(), domain_shared: true },
    tool_scope_config: defaultToolScope(),
    approval_rules: { rules: [{ id: 'rule_lq_1', when: 'email.send', required_approver_level: 3 }] },
    model_chain_config: defaultModelChain('claude-haiku-4-5', ['claude-sonnet-4-6']),
    is_active: true,
    created_by: 'usr_marcelo',
    created_at: days(10),
  },
  {
    id: 'ver_rr_08',
    agent_id: 'agt_refund_resolver',
    version: 8,
    instruction_spec:
      'You are a Refund Resolver. Verify charges, apply policy, issue refund within cap or request approval.',
    memory_scope_config: defaultMemoryScope(),
    tool_scope_config: defaultToolScope(),
    approval_rules: { rules: [{ id: 'rule_rr_1', when: 'stripe.refund > 200', required_approver_level: 3 }] },
    model_chain_config: defaultModelChain('claude-sonnet-4-6'),
    is_active: true,
    created_by: 'usr_priya',
    created_at: days(22),
  },
  {
    id: 'ver_ap_02',
    agent_id: 'agt_access_provisioner',
    version: 2,
    instruction_spec:
      'You are an Access Provisioner. Onboard and offboard SaaS accounts per role template.',
    memory_scope_config: defaultMemoryScope(),
    tool_scope_config: defaultToolScope(),
    approval_rules: { rules: [{ id: 'rule_ap_1', when: 'aws.revoke_user', required_approver_level: 4 }] },
    model_chain_config: defaultModelChain('claude-opus-4-7'),
    is_active: true,
    created_by: 'usr_ada',
    created_at: days(35),
  },
  {
    id: 'ver_ir_05',
    agent_id: 'agt_invoice_reconciler',
    version: 5,
    instruction_spec:
      'You are an Invoice Reconciler. Match invoices to POs, flag variances.',
    memory_scope_config: defaultMemoryScope(),
    tool_scope_config: defaultToolScope(),
    approval_rules: { rules: [] },
    model_chain_config: defaultModelChain('claude-sonnet-4-6'),
    is_active: true,
    created_by: 'usr_ada',
    created_at: days(48),
  },
  {
    id: 'ver_kb_03',
    agent_id: 'agt_kb_sync',
    version: 3,
    instruction_spec:
      'You are a Knowledge Base Sync. Compare internal runbooks to public KB and propose updates.',
    memory_scope_config: defaultMemoryScope(),
    tool_scope_config: defaultToolScope(),
    approval_rules: { rules: [{ id: 'rule_kb_1', when: 'zendesk.publish_article', required_approver_level: 3 }] },
    model_chain_config: defaultModelChain('claude-haiku-4-5'),
    is_active: true,
    created_by: 'usr_priya',
    created_at: days(18),
  },
]

const versionById: Record<string, AgentVersion> = Object.fromEntries(
  agentVersions.map(v => [v.id, v]),
)

// ══════════════════════════════════════════════════ AGENTS

function agent(
  id: string,
  partial: Omit<Agent, 'id' | 'active_version'> & { active_version_id: string | null },
): Agent {
  const { active_version_id, ...rest } = partial
  return {
    id,
    ...rest,
    active_version: active_version_id ? versionById[active_version_id] ?? null : null,
  }
}

export const agents: Agent[] = [
  agent('agt_lead_qualifier', {
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    owner_user_id: 'usr_marcelo',
    name: 'Lead Qualifier',
    description: 'Triages inbound leads, enriches records, drafts personalised outreach.',
    status: 'active',
    created_at: days(62),
    updated_at: days(2),
    active_version_id: 'ver_lq_14',
  }),
  agent('agt_refund_resolver', {
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    owner_user_id: 'usr_priya',
    name: 'Refund Resolver',
    description: 'Reads charges, applies refund policy, issues refunds under cap.',
    status: 'active',
    created_at: days(84),
    updated_at: days(1),
    active_version_id: 'ver_rr_08',
  }),
  agent('agt_access_provisioner', {
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    owner_user_id: 'usr_ada',
    name: 'Access Provisioner',
    description: 'On- and offboards SaaS accounts for new hires and leavers.',
    status: 'active',
    created_at: days(120),
    updated_at: days(4),
    active_version_id: 'ver_ap_02',
  }),
  agent('agt_invoice_reconciler', {
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    owner_user_id: 'usr_ada',
    name: 'Invoice Reconciler',
    description: 'Reconciles invoices against purchase orders, flags variances.',
    status: 'active',
    created_at: days(160),
    updated_at: days(3),
    active_version_id: 'ver_ir_05',
  }),
  agent('agt_kb_sync', {
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    owner_user_id: 'usr_priya',
    name: 'Knowledge Base Sync',
    description: 'Syncs internal runbook changes into the customer-facing help center.',
    status: 'paused',
    created_at: days(75),
    updated_at: days(10),
    active_version_id: 'ver_kb_03',
  }),
  agent('agt_campaign_drafter', {
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    owner_user_id: 'usr_marcelo',
    name: 'Campaign Drafter',
    description: 'Generates email nurture sequences from briefs.',
    status: 'draft',
    created_at: days(5),
    updated_at: days(5),
    active_version_id: null,
  }),
  agent('agt_legacy_triage', {
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    owner_user_id: 'usr_priya',
    name: 'Legacy Triage Bot',
    description: 'Pre-2024 triage agent. Superseded by Lead Qualifier; kept for audit continuity.',
    status: 'archived',
    created_at: days(420),
    updated_at: days(90),
    active_version_id: null,
  }),
]

// ══════════════════════════════════════════════════ TOOL GRANTS

function grant(
  id: string,
  agentId: string,
  tool_name: string,
  mode: ToolGrant['mode'],
  approval_required: boolean,
  config: Record<string, unknown> = {},
): ToolGrant {
  return {
    id,
    scope_type: 'agent',
    scope_id: agentId,
    tool_name,
    mode,
    approval_required,
    config,
  }
}

export const grantsByAgent: Record<string, ToolGrant[]> = {
  agt_lead_qualifier: [
    // Tenant-wide grant inherited by every agent on this tenant.
    {
      id: 'grt_tenant_memory',
      scope_type: 'tenant',
      scope_id: 'ten_acme',
      tool_name: 'memory.read',
      mode: 'read',
      approval_required: false,
      config: {},
    },
    // Domain-wide grant shared by all sales-domain agents.
    {
      id: 'grt_domain_sales_crm',
      scope_type: 'domain',
      scope_id: 'dom_sales',
      tool_name: 'zoho_crm.read_contact',
      mode: 'read',
      approval_required: false,
      config: { scopes: ['contacts:read'] },
    },
    grant('grt_lq_2', 'agt_lead_qualifier', 'zoho_crm.write_deal', 'write', false),
    grant('grt_lq_3', 'agt_lead_qualifier', 'apollo.enrich_contact', 'read', false),
    grant('grt_lq_4', 'agt_lead_qualifier', 'email.send', 'write', true, { max_per_day: 50 }),
    grant('grt_lq_5', 'agt_lead_qualifier', 'memory.write', 'write', false),
  ],
  agt_refund_resolver: [
    grant('grt_rr_1', 'agt_refund_resolver', 'stripe.read_charge', 'read', false),
    grant('grt_rr_2', 'agt_refund_resolver', 'stripe.refund', 'write', true, { max_per_call_usd: 200 }),
    grant('grt_rr_3', 'agt_refund_resolver', 'zendesk.read_ticket', 'read', false),
    // read_write covers the note-append case (read-then-annotate on the same ticket).
    grant('grt_rr_4b', 'agt_refund_resolver', 'zendesk.ticket_notes', 'read_write', true),
    grant('grt_rr_4', 'agt_refund_resolver', 'email.send', 'write', false),
  ],
  agt_access_provisioner: [
    grant('grt_ap_1', 'agt_access_provisioner', 'okta.create_user', 'write', true),
    grant('grt_ap_2', 'agt_access_provisioner', 'okta.read_user', 'read', false),
    grant('grt_ap_3', 'agt_access_provisioner', 'aws.revoke_user', 'write', true),
    grant('grt_ap_4', 'agt_access_provisioner', 'hris.read_employee', 'read', false),
  ],
  agt_invoice_reconciler: [
    grant('grt_ir_1', 'agt_invoice_reconciler', 'quickbooks.read_invoice', 'read', false),
    grant('grt_ir_2', 'agt_invoice_reconciler', 'quickbooks.read_po', 'read', false),
    grant('grt_ir_3', 'agt_invoice_reconciler', 'slack.post_message', 'write', false),
  ],
  agt_kb_sync: [
    grant('grt_kb_1', 'agt_kb_sync', 'notion.read_page', 'read', false),
    grant('grt_kb_2', 'agt_kb_sync', 'zendesk.publish_article', 'write', true),
  ],
  agt_campaign_drafter: [],
}

// ══════════════════════════════════════════════════ TOOL CATALOG (gateway v0.2.0)

export const fxTools: ToolDefinition[] = [
  {
    name: 'stripe.read_charge',
    description: 'Fetch a single Stripe charge by id. Returns amount, currency, status and metadata.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      required: ['charge_id'],
      properties: {
        charge_id: { type: 'string', description: 'Stripe ch_… identifier' },
      },
    },
  },
  {
    name: 'stripe.refund',
    description: 'Issue a refund against a completed charge. Full or partial.',
    default_mode: 'requires_approval',
    input_schema: {
      type: 'object',
      required: ['charge_id', 'amount_usd'],
      properties: {
        charge_id: { type: 'string' },
        amount_usd: { type: 'number', minimum: 0.5 },
        reason: { type: 'string', enum: ['duplicate', 'fraudulent', 'requested_by_customer'] },
      },
    },
  },
  {
    name: 'zoho_crm.read_contact',
    description: 'Look up a CRM contact by email or id.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      properties: {
        email: { type: 'string', format: 'email' },
        contact_id: { type: 'string' },
      },
    },
  },
  {
    name: 'zoho_crm.write_deal',
    description: 'Create or update a CRM deal record.',
    default_mode: 'requires_approval',
    input_schema: {
      type: 'object',
      required: ['account_id', 'stage'],
      properties: {
        account_id: { type: 'string' },
        stage: { type: 'string' },
        amount_usd: { type: 'number' },
      },
    },
  },
  {
    name: 'apollo.enrich_contact',
    description: 'Enrich a contact record with firmographic and technographic data.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      required: ['email'],
      properties: {
        email: { type: 'string', format: 'email' },
      },
    },
  },
  {
    name: 'email.send',
    description: 'Send a transactional email from the tenant’s verified sender domain.',
    default_mode: 'requires_approval',
    input_schema: {
      type: 'object',
      required: ['to', 'subject', 'body'],
      properties: {
        to: { type: 'array', items: { type: 'string', format: 'email' } },
        subject: { type: 'string' },
        body: { type: 'string' },
      },
    },
  },
  {
    name: 'okta.create_user',
    description: 'Provision a new Okta user under a role template.',
    default_mode: 'requires_approval',
    input_schema: {
      type: 'object',
      required: ['email', 'role_template'],
      properties: {
        email: { type: 'string', format: 'email' },
        role_template: { type: 'string' },
      },
    },
  },
  {
    name: 'okta.read_user',
    description: 'Look up an Okta user by id or email.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      properties: {
        email: { type: 'string', format: 'email' },
        user_id: { type: 'string' },
      },
    },
  },
  {
    name: 'aws.revoke_user',
    description: 'Detach all attached IAM policies from a user and disable console access.',
    default_mode: 'denied',
    input_schema: {
      type: 'object',
      required: ['iam_user'],
      properties: {
        iam_user: { type: 'string' },
      },
    },
  },
  {
    name: 'irs.verify_ein',
    description: 'Verify a US Employer Identification Number against the IRS TIN match service.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      required: ['ein', 'legal_name'],
      properties: {
        ein: { type: 'string', pattern: '^\\d{2}-\\d{7}$' },
        legal_name: { type: 'string' },
      },
    },
  },
  {
    name: 'quickbooks.read_invoice',
    description: 'Read invoice rows by id or batch reference.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      properties: {
        invoice_id: { type: 'string' },
        batch_ref: { type: 'string' },
      },
    },
  },
  {
    name: 'slack.post_message',
    description: 'Post a message to a Slack channel.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      required: ['channel', 'text'],
      properties: {
        channel: { type: 'string' },
        text: { type: 'string' },
      },
    },
  },
  // Built-in tools surfaced by the docs/gateway.yaml catalog example. `web_search`
  // is the canonical demo tool from the spec; `kb.lookup` is what the chat-stream
  // mock uses when a user asks the agent to look something up.
  {
    name: 'web_search',
    description: 'Search the public web.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      required: ['query'],
      properties: {
        query: { type: 'string', minLength: 1, maxLength: 500 },
        max_results: { type: 'integer', minimum: 1, maximum: 10, default: 5 },
      },
    },
  },
  {
    name: 'kb.lookup',
    description: 'Search the tenant knowledge base.',
    default_mode: 'read_only',
    input_schema: {
      type: 'object',
      required: ['query'],
      properties: {
        query: { type: 'string', minLength: 1, maxLength: 500 },
      },
    },
  },
]

// ══════════════════════════════════════════════════ TASKS

function task(p: {
  id: string
  domain: string
  type: Task['type']
  status: Task['status']
  created_by: string
  agent: string
  version: string
  title: string
  created_minutes_ago?: number
  updated_minutes_ago?: number
}): Task {
  return {
    id: p.id,
    tenant_id: 'ten_acme',
    domain_id: p.domain,
    type: p.type,
    status: p.status,
    created_by: p.created_by,
    assigned_agent_id: p.agent,
    assigned_agent_version_id: p.version,
    title: p.title,
    created_at: mins(p.created_minutes_ago ?? 60),
    updated_at: mins(p.updated_minutes_ago ?? 10),
  }
}

export const tasks: Task[] = [
  task({
    id: 'tsk_4081',
    domain: 'dom_support',
    type: 'one_time',
    status: 'running',
    created_by: 'usr_priya',
    agent: 'agt_refund_resolver',
    version: 'ver_rr_08',
    title: 'Refund #SR-2204 — Eliza Voss',
    created_minutes_ago: 12,
    updated_minutes_ago: 1,
  }),
  task({
    id: 'tsk_4080',
    domain: 'dom_sales',
    type: 'one_time',
    status: 'running',
    created_by: 'usr_marcelo',
    agent: 'agt_lead_qualifier',
    version: 'ver_lq_14',
    title: 'Triage batch · inbound forms 10:00–11:00',
    created_minutes_ago: 8,
    updated_minutes_ago: 2,
  }),
  task({
    id: 'tsk_4079',
    domain: 'dom_hq',
    type: 'one_time',
    status: 'completed',
    created_by: 'usr_ada',
    agent: 'agt_invoice_reconciler',
    version: 'ver_ir_05',
    title: 'Reconcile Oct batch · 38 invoices',
    created_minutes_ago: 120,
    updated_minutes_ago: 60,
  }),
  task({
    id: 'tsk_4077',
    domain: 'dom_hq',
    type: 'one_time',
    status: 'running',
    created_by: 'usr_ada',
    agent: 'agt_access_provisioner',
    version: 'ver_ap_02',
    title: 'Offboard L.Chu — revoke all access',
    created_minutes_ago: 300,
    updated_minutes_ago: 240,
  }),
  task({
    id: 'tsk_4076',
    domain: 'dom_hq',
    type: 'one_time',
    status: 'failed',
    created_by: 'usr_ada',
    agent: 'agt_invoice_reconciler',
    version: 'ver_ir_05',
    title: 'Vendor onboarding — Fieldston Partners',
    created_minutes_ago: 360,
    updated_minutes_ago: 300,
  }),
  task({
    id: 'tsk_4074',
    domain: 'dom_support',
    type: 'one_time',
    status: 'completed',
    created_by: 'usr_priya',
    agent: 'agt_refund_resolver',
    version: 'ver_rr_08',
    title: 'Refund #SR-2201 — $89 broken in transit',
    created_minutes_ago: 420,
    updated_minutes_ago: 360,
  }),
  task({
    id: 'tsk_4070',
    domain: 'dom_sales',
    type: 'schedule',
    status: 'pending',
    created_by: 'usr_marcelo',
    agent: 'agt_lead_qualifier',
    version: 'ver_lq_14',
    title: 'Rescore stalled leads · daily 08:00',
    created_minutes_ago: 1440,
    updated_minutes_ago: 1440,
  }),
  task({
    id: 'tsk_4068',
    domain: 'dom_support',
    type: 'schedule',
    status: 'pending',
    created_by: 'usr_priya',
    agent: 'agt_kb_sync',
    version: 'ver_kb_03',
    title: 'Nightly KB diff · 03:00 UTC',
    created_minutes_ago: 4320,
    updated_minutes_ago: 4320,
  }),
  task({
    id: 'tsk_4075',
    domain: 'dom_support',
    type: 'chat',
    status: 'running',
    created_by: 'usr_priya',
    agent: 'agt_refund_resolver',
    version: 'ver_rr_08',
    title: 'Chat · customer follow-up on SR-2197',
    created_minutes_ago: 18,
    updated_minutes_ago: 3,
  }),
  task({
    id: 'tsk_4071',
    domain: 'dom_hq',
    type: 'one_time',
    status: 'cancelled',
    created_by: 'usr_ada',
    agent: 'agt_access_provisioner',
    version: 'ver_ap_02',
    title: 'Offboard V.Ramos — cancelled (employee re-hired)',
    created_minutes_ago: 2880,
    updated_minutes_ago: 2600,
  }),
]

// ══════════════════════════════════════════════════ RUN STEPS / RUNS

function step(p: {
  id: string
  kind: RunStep['step_type']
  status: string
  model?: string
  tool?: string
  input?: Record<string, unknown>
  output?: Record<string, unknown>
  cost?: number
  tokens_in?: number
  tokens_out?: number
  duration_ms?: number
  created_minutes_ago: number
  completed_minutes_ago?: number | null
}): RunStep {
  return {
    id: p.id,
    step_type: p.kind,
    status: p.status,
    model_name: p.model ?? null,
    tool_name: p.tool ?? null,
    input_ref: p.input ?? null,
    output_ref: p.output ?? null,
    cost_usd: p.cost ?? null,
    tokens_in: p.tokens_in ?? null,
    tokens_out: p.tokens_out ?? null,
    duration_ms: p.duration_ms ?? null,
    created_at: mins(p.created_minutes_ago),
    completed_at:
      p.completed_minutes_ago === null
        ? null
        : mins(p.completed_minutes_ago ?? p.created_minutes_ago),
  }
}

export const runs: Record<string, Run> = {
  run_4081: {
    id: 'run_4081',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    task_id: 'tsk_4081',
    agent_version_id: 'ver_rr_08',
    status: 'suspended',
    suspended_stage: 'approval_gate · stripe.refund',
    started_at: mins(12),
    ended_at: null,
    total_cost_usd: 0.18,
    total_tokens_in: 3420,
    total_tokens_out: 810,
    error_message: null,
    created_at: mins(12),
    steps: [
      step({
        id: 'stp_run_4081_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-sonnet-4-6',
        input: { prompt: 'Process refund request SR-2204 ($412, Eliza Voss)' },
        output: { plan: 'verify → policy → approval → notify' },
        cost: 0.04,
        tokens_in: 620,
        tokens_out: 140,
        duration_ms: 820,
        created_minutes_ago: 12,
        completed_minutes_ago: 12,
      }),
      step({
        id: 'stp_run_4081_002',
        kind: 'memory_read',
        status: 'ok',
        tool: 'memory.read',
        input: { scope: 'user_facts', key: 'cus_N0a2vX' },
        output: { hits: 3 },
        duration_ms: 90,
        created_minutes_ago: 12,
        completed_minutes_ago: 12,
      }),
      step({
        id: 'stp_run_4081_003',
        kind: 'tool_call',
        status: 'ok',
        tool: 'stripe.read_charge',
        input: { charge_id: 'ch_3P8fL2' },
        output: { status: 'succeeded', amount_usd: 412 },
        cost: 0.0,
        duration_ms: 310,
        created_minutes_ago: 11,
        completed_minutes_ago: 11,
      }),
      step({
        id: 'stp_run_4081_004',
        kind: 'validation',
        status: 'ok',
        tool: 'policy.check',
        input: { rule_id: 'rule_rr_1' },
        output: { verdict: 'approval_required', reason: 'amount > $200 cap' },
        duration_ms: 40,
        created_minutes_ago: 11,
        completed_minutes_ago: 11,
      }),
      step({
        id: 'stp_run_4081_005',
        kind: 'tool_call',
        status: 'blocked',
        tool: 'stripe.refund',
        input: { charge_id: 'ch_3P8fL2', amount_usd: 412 },
        duration_ms: 0,
        created_minutes_ago: 10,
        completed_minutes_ago: 10,
      }),
      step({
        id: 'stp_run_4081_006',
        kind: 'approval_gate',
        status: 'pending',
        input: { approval_id: 'apv_9021' },
        created_minutes_ago: 10,
        completed_minutes_ago: null,
      }),
    ],
  },
  run_4080: {
    id: 'run_4080',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    task_id: 'tsk_4080',
    agent_version_id: 'ver_lq_14',
    status: 'running',
    suspended_stage: null,
    started_at: mins(8),
    ended_at: null,
    total_cost_usd: 0.84,
    total_tokens_in: 18420,
    total_tokens_out: 4210,
    error_message: null,
    created_at: mins(8),
    steps: [
      step({
        id: 'stp_run_4080_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-haiku-4-5',
        input: { prompt: 'Score 24 inbound forms' },
        output: { plan: 'score · enrich · outreach top 8' },
        cost: 0.08,
        tokens_in: 1400,
        tokens_out: 320,
        duration_ms: 1200,
        created_minutes_ago: 8,
        completed_minutes_ago: 7,
      }),
      step({
        id: 'stp_run_4080_002',
        kind: 'tool_call',
        status: 'ok',
        tool: 'apollo.enrich_contact',
        input: { batch_size: 24 },
        output: { enriched: 24 },
        cost: 0.24,
        duration_ms: 6400,
        created_minutes_ago: 7,
        completed_minutes_ago: 6,
      }),
      step({
        id: 'stp_run_4080_003',
        kind: 'memory_write',
        status: 'ok',
        tool: 'memory.write',
        input: { scope: 'domain_shared', count: 17 },
        duration_ms: 120,
        created_minutes_ago: 6,
        completed_minutes_ago: 6,
      }),
      step({
        id: 'stp_run_4080_004',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-haiku-4-5',
        output: { high_fit: 8, mid_fit: 9, low_fit: 7 },
        cost: 0.12,
        tokens_in: 3200,
        tokens_out: 540,
        duration_ms: 1800,
        created_minutes_ago: 5,
        completed_minutes_ago: 5,
      }),
      step({
        id: 'stp_run_4080_005',
        kind: 'tool_call',
        status: 'running',
        tool: 'email.send',
        input: { batch: 8 },
        created_minutes_ago: 3,
        completed_minutes_ago: null,
      }),
    ],
  },
  run_4079: {
    id: 'run_4079',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    task_id: 'tsk_4079',
    agent_version_id: 'ver_ir_05',
    status: 'completed',
    suspended_stage: null,
    started_at: hrs(2),
    ended_at: hrs(1),
    total_cost_usd: 2.18,
    total_tokens_in: 48200,
    total_tokens_out: 9800,
    error_message: null,
    created_at: hrs(2),
    steps: [
      step({
        id: 'stp_run_4079_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-sonnet-4-6',
        input: { invoices: 38 },
        cost: 0.48,
        tokens_in: 12400,
        tokens_out: 2200,
        duration_ms: 3100,
        created_minutes_ago: 120,
        completed_minutes_ago: 119,
      }),
      step({
        id: 'stp_run_4079_002',
        kind: 'tool_call',
        status: 'ok',
        tool: 'quickbooks.read_invoice',
        input: { count: 38 },
        output: { loaded: 38 },
        duration_ms: 4800,
        created_minutes_ago: 118,
        completed_minutes_ago: 116,
      }),
      step({
        id: 'stp_run_4079_003',
        kind: 'tool_call',
        status: 'ok',
        tool: 'quickbooks.read_po',
        input: { count: 38 },
        output: { loaded: 38 },
        duration_ms: 3200,
        created_minutes_ago: 116,
        completed_minutes_ago: 114,
      }),
      step({
        id: 'stp_run_4079_004',
        kind: 'validation',
        status: 'ok',
        tool: 'policy.check',
        output: { verdict: 'pass', variances: 1 },
        duration_ms: 60,
        created_minutes_ago: 113,
        completed_minutes_ago: 113,
      }),
      step({
        id: 'stp_run_4079_005',
        kind: 'tool_call',
        status: 'ok',
        tool: 'slack.post_message',
        input: { channel: '#finance-alerts', lines: 8 },
        duration_ms: 210,
        created_minutes_ago: 112,
        completed_minutes_ago: 112,
      }),
    ],
  },
  run_4077: {
    id: 'run_4077',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    task_id: 'tsk_4077',
    agent_version_id: 'ver_ap_02',
    status: 'suspended',
    suspended_stage: 'approval_gate · aws.revoke_user',
    started_at: hrs(5),
    ended_at: null,
    total_cost_usd: 0.22,
    total_tokens_in: 4820,
    total_tokens_out: 620,
    error_message: null,
    created_at: hrs(5),
    steps: [
      step({
        id: 'stp_run_4077_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-opus-4-7',
        input: { employee_id: '20184' },
        cost: 0.14,
        tokens_in: 2400,
        tokens_out: 380,
        duration_ms: 2400,
        created_minutes_ago: 300,
        completed_minutes_ago: 299,
      }),
      step({
        id: 'stp_run_4077_002',
        kind: 'tool_call',
        status: 'ok',
        tool: 'hris.read_employee',
        input: { employee_id: '20184' },
        output: { exit_date: 'today' },
        duration_ms: 220,
        created_minutes_ago: 298,
        completed_minutes_ago: 298,
      }),
      step({
        id: 'stp_run_4077_003',
        kind: 'tool_call',
        status: 'blocked',
        tool: 'aws.revoke_user',
        input: { iam_user: 'lchu@acme', attached_policies: 12 },
        created_minutes_ago: 295,
        completed_minutes_ago: 295,
      }),
      step({
        id: 'stp_run_4077_004',
        kind: 'approval_gate',
        status: 'pending',
        input: { approval_id: 'apv_9022' },
        created_minutes_ago: 294,
        completed_minutes_ago: null,
      }),
    ],
  },
  run_4076: {
    id: 'run_4076',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    task_id: 'tsk_4076',
    agent_version_id: 'ver_ir_05',
    status: 'failed',
    suspended_stage: null,
    started_at: hrs(6),
    ended_at: hrs(5),
    total_cost_usd: 0.08,
    total_tokens_in: 2840,
    total_tokens_out: 410,
    error_message:
      'IRS EIN verification returned mismatch with declared legal name ("Fieldston Partners LLC" vs filed "Fieldston Holdings Partners LLC").',
    error_kind: 'tool_error',
    tool_errors: [
      {
        tool: 'irs.verify_ein',
        status: 'error',
        message: 'TIN/name mismatch: declared legal name does not match IRS record.',
        at: hrs(5.9),
        tool_call_id: 'stp_run_4076_003',
      },
      {
        tool: 'aws.revoke_user',
        status: 'denied',
        message: 'Tool is denied by the active policy snapshot (requires admin grant).',
        at: hrs(5.85),
        tool_call_id: null,
      },
    ],
    created_at: hrs(6),
    steps: [
      step({
        id: 'stp_run_4076_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-sonnet-4-6',
        input: { vendor: 'Fieldston Partners LLC' },
        cost: 0.05,
        tokens_in: 1800,
        tokens_out: 260,
        duration_ms: 2100,
        created_minutes_ago: 360,
        completed_minutes_ago: 359,
      }),
      step({
        id: 'stp_run_4076_002',
        kind: 'tool_call',
        status: 'ok',
        tool: 'docs.parse_w9',
        input: { doc_id: 'doc_w9_fp' },
        output: { ein: '**-*******', legal_name: 'Fieldston Partners LLC' },
        duration_ms: 1200,
        created_minutes_ago: 358,
        completed_minutes_ago: 357,
      }),
      step({
        id: 'stp_run_4076_003',
        kind: 'tool_call',
        status: 'failed',
        tool: 'irs.verify_ein',
        input: { ein: '**-*******' },
        output: { error: 'mismatch' },
        duration_ms: 820,
        created_minutes_ago: 356,
        completed_minutes_ago: 356,
      }),
      step({
        id: 'stp_run_4076_004',
        kind: 'validation',
        status: 'failed',
        tool: 'policy.check',
        output: { verdict: 'block', reason: 'verification failed' },
        duration_ms: 40,
        created_minutes_ago: 355,
        completed_minutes_ago: 355,
      }),
    ],
  },
  // Standalone run (no task_id) per ADR-0003 + completed_with_errors status per v0.2.0.
  run_4082: {
    id: 'run_4082',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    task_id: null,
    agent_version_id: 'ver_lq_14',
    status: 'completed_with_errors',
    suspended_stage: null,
    started_at: hrs(1.5),
    ended_at: hrs(1),
    total_cost_usd: 0.62,
    total_tokens_in: 14200,
    total_tokens_out: 3100,
    error_message: 'Partial success: 6 / 8 outreach drafts produced; 2 enrichment calls timed out.',
    error_kind: 'tool_error',
    tool_errors: [
      {
        tool: 'apollo.enrich_contact',
        status: 'timeout',
        message: 'Upstream timeout after 12s on contact a.weiss@northwind.example.',
        at: hrs(1.3),
        tool_call_id: 'stp_run_4082_003',
      },
      {
        tool: 'apollo.enrich_contact',
        status: 'timeout',
        message: 'Upstream timeout after 12s on contact j.okafor@acme-retail.example.',
        at: hrs(1.25),
        tool_call_id: 'stp_run_4082_004',
      },
    ],
    created_at: hrs(1.5),
    steps: [
      step({
        id: 'stp_run_4082_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-haiku-4-5',
        input: { prompt: 'Draft outreach for 8 inbound leads' },
        output: { plan: 'enrich · draft · review' },
        cost: 0.09,
        tokens_in: 1800,
        tokens_out: 420,
        duration_ms: 1400,
        created_minutes_ago: 90,
        completed_minutes_ago: 89,
      }),
      step({
        id: 'stp_run_4082_002',
        kind: 'tool_call',
        status: 'ok',
        tool: 'apollo.enrich_contact',
        input: { batch_size: 6 },
        output: { enriched: 6 },
        cost: 0.18,
        duration_ms: 5200,
        created_minutes_ago: 88,
        completed_minutes_ago: 86,
      }),
      step({
        id: 'stp_run_4082_003',
        kind: 'tool_call',
        status: 'failed',
        tool: 'apollo.enrich_contact',
        input: { email: 'a.weiss@northwind.example' },
        output: { error: 'timeout' },
        duration_ms: 12000,
        created_minutes_ago: 85,
        completed_minutes_ago: 83,
      }),
      step({
        id: 'stp_run_4082_004',
        kind: 'tool_call',
        status: 'failed',
        tool: 'apollo.enrich_contact',
        input: { email: 'j.okafor@acme-retail.example' },
        output: { error: 'timeout' },
        duration_ms: 12000,
        created_minutes_ago: 83,
        completed_minutes_ago: 81,
      }),
      step({
        id: 'stp_run_4082_005',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-haiku-4-5',
        output: { drafts: 6, skipped: 2 },
        cost: 0.35,
        tokens_in: 12400,
        tokens_out: 2680,
        duration_ms: 3100,
        created_minutes_ago: 80,
        completed_minutes_ago: 78,
      }),
    ],
  },
  // Fresh run that hasn't started executing yet — orchestrator dispatch queue.
  run_4083: {
    id: 'run_4083',
    tenant_id: 'ten_acme',
    domain_id: 'dom_support',
    task_id: 'tsk_4075',
    agent_version_id: 'ver_rr_08',
    status: 'pending',
    suspended_stage: null,
    started_at: null,
    ended_at: null,
    total_cost_usd: 0,
    total_tokens_in: 0,
    total_tokens_out: 0,
    error_message: null,
    created_at: mins(2),
    steps: [],
  },
  // Cancelled run — user/API aborted before completion.
  run_4078: {
    id: 'run_4078',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    task_id: 'tsk_4071',
    agent_version_id: 'ver_ap_02',
    status: 'cancelled',
    suspended_stage: null,
    started_at: hrs(48),
    ended_at: hrs(47.8),
    total_cost_usd: 0.02,
    total_tokens_in: 420,
    total_tokens_out: 80,
    error_message: 'Cancelled by operator — employee re-hired before offboarding completed.',
    error_kind: 'cancelled',
    created_at: hrs(48),
    steps: [
      step({
        id: 'stp_run_4078_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-opus-4-7',
        input: { employee_id: '20092' },
        cost: 0.02,
        tokens_in: 420,
        tokens_out: 80,
        duration_ms: 900,
        created_minutes_ago: 2880,
        completed_minutes_ago: 2879,
      }),
      step({
        id: 'stp_run_4078_002',
        kind: 'tool_call',
        status: 'blocked',
        tool: 'aws.revoke_user',
        input: { iam_user: 'vramos@acme' },
        created_minutes_ago: 2878,
        completed_minutes_ago: 2878,
      }),
    ],
  },
  // Failed via orchestrator error — the orchestrator itself crashed, not a tool.
  run_4075: {
    id: 'run_4075',
    tenant_id: 'ten_acme',
    domain_id: 'dom_sales',
    task_id: null,
    agent_version_id: 'ver_lq_14',
    status: 'failed',
    suspended_stage: null,
    started_at: hrs(22),
    ended_at: hrs(22),
    total_cost_usd: 0.04,
    total_tokens_in: 1100,
    total_tokens_out: 0,
    error_message: 'Agent stopped before finishing this step. No output was produced.',
    error_kind: 'orchestrator_error',
    created_at: hrs(22),
    steps: [
      step({
        id: 'stp_run_4075_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-haiku-4-5',
        input: { prompt: 'Score batch · inbound 14:00' },
        cost: 0.04,
        tokens_in: 1100,
        tokens_out: 0,
        duration_ms: 1600,
        created_minutes_ago: 1320,
        completed_minutes_ago: 1319,
      }),
    ],
  },
  // Failed via timeout — orchestrator hit the per-run wall-clock cap.
  run_4073: {
    id: 'run_4073',
    tenant_id: 'ten_acme',
    domain_id: 'dom_hq',
    task_id: 'tsk_4073',
    agent_version_id: 'ver_ir_05',
    status: 'failed',
    suspended_stage: null,
    started_at: hrs(70),
    ended_at: hrs(69.5),
    total_cost_usd: 0.88,
    total_tokens_in: 18200,
    total_tokens_out: 3600,
    error_message: 'Run exceeded 30-minute wall-clock cap. Partial output discarded.',
    error_kind: 'timeout',
    created_at: hrs(70),
    steps: [
      step({
        id: 'stp_run_4073_001',
        kind: 'llm_call',
        status: 'ok',
        model: 'claude-sonnet-4-6',
        input: { batch_size: 220 },
        cost: 0.88,
        tokens_in: 18200,
        tokens_out: 3600,
        duration_ms: 1740000,
        created_minutes_ago: 4200,
        completed_minutes_ago: 4170,
      }),
      step({
        id: 'stp_run_4073_002',
        kind: 'tool_call',
        status: 'failed',
        tool: 'quickbooks.read_invoice',
        input: { batch_ref: 'Q4-recon' },
        output: { error: 'deadline_exceeded' },
        duration_ms: 1800000,
        created_minutes_ago: 4170,
        completed_minutes_ago: 4140,
      }),
    ],
  },
}

// ══════════════════════════════════════════════════ APPROVALS

export const approvals: ApprovalRequest[] = [
  {
    id: 'apv_9021',
    run_id: 'run_4081',
    task_id: 'tsk_4081',
    tenant_id: 'ten_acme',
    requested_action: 'stripe.refund · $412 on charge ch_3P8fL2 (order #44021)',
    requested_by: 'usr_priya',
    requested_by_name: 'Priya Vasan',
    approver_role: 'domain_admin',
    approver_user_id: 'usr_marcelo',
    status: 'pending',
    reason: null,
    evidence_ref: {
      charge_id: 'ch_3P8fL2',
      order_id: '#44021',
      amount_usd: 412,
      reason: 'Customer-reported duplicate charge',
    },
    expires_at: future(230),
    resolved_at: null,
    created_at: mins(9),
  },
  {
    id: 'apv_9022',
    run_id: 'run_4077',
    task_id: 'tsk_4077',
    tenant_id: 'ten_acme',
    requested_action: 'aws.revoke_user · IAM user lchu@acme (12 attached policies)',
    requested_by: 'usr_ada',
    requested_by_name: 'Ada Fernsby',
    approver_role: 'admin',
    approver_user_id: null,
    status: 'pending',
    reason: null,
    evidence_ref: {
      iam_user: 'lchu@acme',
      attached_policies: 12,
      active_sessions: 0,
      last_login: '8 days ago',
    },
    expires_at: future(120),
    resolved_at: null,
    created_at: hrs(4),
  },
  // Approval for a standalone run (task_id is null per ADR-0003).
  {
    id: 'apv_9024',
    run_id: 'run_4082',
    task_id: null,
    tenant_id: 'ten_acme',
    requested_action: 'email.send batch × 6 · outreach drafts (partial — 2 contacts skipped after enrich timeouts)',
    requested_by: 'usr_marcelo',
    requested_by_name: 'Marcelo Ito',
    approver_role: 'domain_admin',
    approver_user_id: null,
    status: 'pending',
    reason: null,
    evidence_ref: {
      recipients: 6,
      skipped: 2,
      skipped_reason: 'apollo.enrich_contact timeout',
      sample_subject_1: 'Quick note for you, Alex',
    },
    expires_at: future(180),
    resolved_at: null,
    created_at: mins(55),
  },
  {
    id: 'apv_9023',
    run_id: 'run_4080',
    task_id: 'tsk_4080',
    tenant_id: 'ten_acme',
    requested_action: 'email.send batch × 8 · personalised outreach to high-fit leads',
    requested_by: 'usr_marcelo',
    requested_by_name: 'Marcelo Ito',
    approver_role: 'domain_admin',
    approver_user_id: null,
    status: 'pending',
    reason: null,
    evidence_ref: {
      recipients: 8,
      sample_subject_1: 'Quick note on your request, Priya',
      sample_subject_2: "Saw Northwind's latest — relevant?",
    },
    expires_at: future(360),
    resolved_at: null,
    created_at: mins(3),
  },
  {
    id: 'apv_9014',
    run_id: 'run_4050',
    task_id: 'tsk_4050',
    tenant_id: 'ten_acme',
    requested_action: 'stripe.refund · $280 duplicate subscription charge',
    requested_by: 'usr_priya',
    requested_by_name: 'Priya Vasan',
    approver_role: 'domain_admin',
    approver_user_id: 'usr_marcelo',
    status: 'approved',
    reason: 'Approved — loyal customer, clear double-charge in logs.',
    evidence_ref: { charge_id: 'ch_2X8lM1', amount_usd: 280 },
    expires_at: hrs(18),
    resolved_at: hrs(23),
    created_at: hrs(24),
  },
  {
    id: 'apv_9011',
    run_id: 'run_4030',
    task_id: 'tsk_4030',
    tenant_id: 'ten_acme',
    requested_action: 'brex.create_vendor · Taubman & Co · Net-30 ACH',
    requested_by: 'usr_ada',
    requested_by_name: 'Ada Fernsby',
    approver_role: 'domain_admin',
    approver_user_id: 'usr_marcelo',
    status: 'rejected',
    reason: 'Reject — vendor already exists under a different legal name.',
    evidence_ref: { legal_name: 'Taubman & Co', terms: 'Net-30' },
    expires_at: days(1),
    resolved_at: days(2),
    created_at: days(2),
  },
  {
    id: 'apv_9005',
    run_id: 'run_4010',
    task_id: 'tsk_4010',
    tenant_id: 'ten_acme',
    requested_action: 'okta.create_user · new hire · role template "sales_ae"',
    requested_by: 'usr_ada',
    requested_by_name: 'Ada Fernsby',
    approver_role: 'admin',
    approver_user_id: null,
    status: 'expired',
    reason: null,
    evidence_ref: { user_email: 'e.mapondera@acme.local', role_template: 'sales_ae' },
    expires_at: days(4),
    resolved_at: null,
    created_at: days(5),
  },
  {
    id: 'apv_9001',
    run_id: 'run_4078',
    task_id: 'tsk_4071',
    tenant_id: 'ten_acme',
    requested_action: 'aws.revoke_user · IAM user vramos@acme (offboarding)',
    requested_by: 'usr_ada',
    requested_by_name: 'Ada Fernsby',
    approver_role: 'admin',
    approver_user_id: null,
    status: 'cancelled',
    reason: 'Cancelled — employee re-hired before offboarding completed.',
    evidence_ref: { iam_user: 'vramos@acme', attached_policies: 8 },
    expires_at: hrs(47),
    resolved_at: hrs(47.8),
    created_at: hrs(48),
  },
]

// ══════════════════════════════════════════════════ CHATS (docs/gateway.yaml)

export const chats: Chat[] = [
  {
    id: 'cht_3801',
    tenant_id: 'ten_acme',
    agent_id: 'agt_lead_qualifier',
    agent_version_id: 'ver_lq_14',
    created_by: 'usr_marcelo',
    model: 'claude-haiku-4-5',
    title: 'Lead triage debrief — Friday batch',
    status: 'active',
    started_at: mins(45),
    updated_at: mins(2),
    ended_at: null,
    total_cost_usd: 0.42,
    total_tokens_in: 6840,
    total_tokens_out: 1520,
  },
  {
    id: 'cht_3795',
    tenant_id: 'ten_acme',
    agent_id: 'agt_refund_resolver',
    agent_version_id: 'ver_rr_08',
    created_by: 'usr_priya',
    model: 'claude-sonnet-4-6',
    title: 'Refund question — Eliza Voss SR-2204',
    status: 'closed',
    started_at: hrs(20),
    updated_at: hrs(19),
    ended_at: hrs(19),
    total_cost_usd: 0.18,
    total_tokens_in: 3120,
    total_tokens_out: 740,
  },
  {
    id: 'cht_3790',
    tenant_id: 'ten_acme',
    agent_id: 'agt_kb_sync',
    agent_version_id: 'ver_kb_03',
    created_by: 'usr_ada',
    model: 'claude-haiku-4-5',
    title: 'Quick fact-check on Q4 KB drift',
    status: 'active',
    started_at: hrs(4),
    updated_at: hrs(3.6),
    ended_at: null,
    total_cost_usd: 0.09,
    total_tokens_in: 1840,
    total_tokens_out: 420,
  },
]

// chat_id → ordered messages (newest-first ordering applied at API layer).
export const chatMessages: Record<string, ChatMessage[]> = {
  cht_3801: [
    {
      id: 'msg_3801_1',
      chat_id: 'cht_3801',
      role: 'user',
      content: 'What did you find for our top 3 enterprise leads this week?',
      tool_calls: null,
      tool_call_id: null,
      tool_name: null,
      cost_usd: null,
      tokens_in: null,
      tokens_out: null,
      created_at: mins(45),
    },
    {
      id: 'msg_3801_2',
      chat_id: 'cht_3801',
      role: 'assistant',
      content: 'Pulling enriched contact records and pipeline stages from the CRM now.',
      tool_calls: [
        {
          id: 'tcl_3801_a',
          name: 'zoho_crm.read_contact',
          args: { batch: ['Northwind', 'Adatum', 'Contoso'], fields: ['stage', 'pipeline_usd', 'last_touch'] },
        },
      ],
      tool_call_id: null,
      tool_name: null,
      cost_usd: 0.06,
      tokens_in: 820,
      tokens_out: 180,
      created_at: mins(44),
    },
    {
      id: 'msg_3801_3',
      chat_id: 'cht_3801',
      role: 'tool',
      content: JSON.stringify({
        Northwind: { stage: 'proposal', pipeline_usd: 420_000, last_touch: '2026-04-22' },
        Adatum: { stage: 'proposal', pipeline_usd: 310_000, last_touch: '2026-04-23' },
        Contoso: { stage: 'discovery', pipeline_usd: 280_000, last_touch: '2026-04-21' },
      }),
      tool_calls: null,
      tool_call_id: 'tcl_3801_a',
      tool_name: 'zoho_crm.read_contact',
      cost_usd: null,
      tokens_in: null,
      tokens_out: null,
      created_at: mins(44),
    },
    {
      id: 'msg_3801_4',
      chat_id: 'cht_3801',
      role: 'assistant',
      content:
        'Top three this week:\n\n• **Northwind** — proposal stage, $420k pipeline, last touch Apr 22.\n• **Adatum** — proposal stage, $310k pipeline, last touch Apr 23.\n• **Contoso** — still in discovery, $280k pipeline, last touch Apr 21.\n\nNorthwind and Adatum are both warm enough to schedule the close call this week. Contoso needs another discovery round before pricing.',
      tool_calls: null,
      tool_call_id: null,
      tool_name: null,
      cost_usd: 0.12,
      tokens_in: 2400,
      tokens_out: 460,
      created_at: mins(43),
    },
    {
      id: 'msg_3801_5',
      chat_id: 'cht_3801',
      role: 'user',
      content: 'Draft the close-call invite for Northwind. Keep it short.',
      tool_calls: null,
      tool_call_id: null,
      tool_name: null,
      cost_usd: null,
      tokens_in: null,
      tokens_out: null,
      created_at: mins(3),
    },
    {
      id: 'msg_3801_6',
      chat_id: 'cht_3801',
      role: 'assistant',
      content:
        'Subject: Locking in the Northwind close — 30 minutes this week?\n\nHi team — we\'re at proposal with Northwind ($420k), last touch Apr 22. Proposing a 30-minute close call Thursday or Friday. I\'ll bring the redlined contract and the security questionnaire responses; you bring the executive sponsor sign-off and the pricing approval. Reply with a slot and I\'ll send the invite.',
      tool_calls: null,
      tool_call_id: null,
      tool_name: null,
      cost_usd: 0.24,
      tokens_in: 3620,
      tokens_out: 880,
      created_at: mins(2),
    },
  ],
  cht_3795: [
    {
      id: 'msg_3795_1',
      chat_id: 'cht_3795',
      role: 'user',
      content: 'Customer Eliza Voss says she was double-charged on order #44021. Can you check?',
      tool_calls: null,
      tool_call_id: null,
      tool_name: null,
      cost_usd: null,
      tokens_in: null,
      tokens_out: null,
      created_at: hrs(20),
    },
    {
      id: 'msg_3795_2',
      chat_id: 'cht_3795',
      role: 'assistant',
      content: 'Looking up the charge in Stripe.',
      tool_calls: [
        { id: 'tcl_3795_a', name: 'stripe.read_charge', args: { charge_id: 'ch_3P8fL2' } },
      ],
      tool_call_id: null,
      tool_name: null,
      cost_usd: 0.04,
      tokens_in: 620,
      tokens_out: 140,
      created_at: hrs(20),
    },
    {
      id: 'msg_3795_3',
      chat_id: 'cht_3795',
      role: 'tool',
      content: JSON.stringify({ status: 'succeeded', amount_usd: 412, customer: 'Eliza Voss', order_id: '#44021' }),
      tool_calls: null,
      tool_call_id: 'tcl_3795_a',
      tool_name: 'stripe.read_charge',
      cost_usd: null,
      tokens_in: null,
      tokens_out: null,
      created_at: hrs(20),
    },
    {
      id: 'msg_3795_4',
      chat_id: 'cht_3795',
      role: 'assistant',
      content:
        'I see one successful $412 charge on order #44021 — no duplicate visible in Stripe. Possible causes: a pending authorization that fell off, or a separate retry attempt that did not complete. I drafted a refund request for review (it crosses the $200 cap and needs Marcelo to sign off). The refund is now in the approvals queue.',
      tool_calls: null,
      tool_call_id: null,
      tool_name: null,
      cost_usd: 0.14,
      tokens_in: 2500,
      tokens_out: 600,
      created_at: hrs(19),
    },
  ],
  cht_3790: [
    {
      id: 'msg_3790_1',
      chat_id: 'cht_3790',
      role: 'user',
      content: 'Is the help-center article on bulk export still aligned with the runbook from October?',
      tool_calls: null,
      tool_call_id: null,
      tool_name: null,
      cost_usd: null,
      tokens_in: null,
      tokens_out: null,
      created_at: hrs(4),
    },
    {
      id: 'msg_3790_2',
      chat_id: 'cht_3790',
      role: 'assistant',
      content:
        'Diff against the October runbook: the public article still references the old 200-row export limit. Internal runbook bumped that to 1,000 rows on Oct 18. I can prepare the article update — it\'ll need an admin to publish.',
      tool_calls: null,
      tool_call_id: null,
      tool_name: null,
      cost_usd: 0.09,
      tokens_in: 1840,
      tokens_out: 420,
      created_at: hrs(3.6),
    },
  ],
}

// ══════════════════════════════════════════════════ SPEND

function row(id: string, label: string, total: number, runs: number, tokensIn: number, tokensOut: number): SpendRow {
  return {
    id,
    label,
    total_usd: total,
    total_tokens_in: tokensIn,
    total_tokens_out: tokensOut,
    run_count: runs,
    spend_date: new Date().toISOString().slice(0, 10),
  }
}

const byAgentBase: SpendRow[] = [
  row('agt_lead_qualifier', 'Lead Qualifier', 1840, 62, 280_000, 64_000),
  row('agt_refund_resolver', 'Refund Resolver', 640, 41, 120_000, 28_000),
  row('agt_invoice_reconciler', 'Invoice Reconciler', 2180, 18, 420_000, 94_000),
  row('agt_access_provisioner', 'Access Provisioner', 420, 9, 80_000, 14_000),
  row('agt_kb_sync', 'Knowledge Base Sync', 210, 28, 40_000, 10_000),
]

const byUserBase: SpendRow[] = [
  row('usr_marcelo', 'Marcelo Ito', 1900, 74, 320_000, 72_000),
  row('usr_priya', 'Priya Vasan', 870, 62, 160_000, 38_000),
  row('usr_ada', 'Ada Fernsby', 2600, 27, 500_000, 112_000),
]

const RANGE_MULTIPLIER: Record<SpendRange, number> = { '1d': 0.03, '7d': 0.22, '30d': 1, '90d': 2.8 }

function scaleRow(r: SpendRow, m: number): SpendRow {
  return {
    ...r,
    total_usd: Math.round(r.total_usd * m * 100) / 100,
    total_tokens_in: Math.round(r.total_tokens_in * m),
    total_tokens_out: Math.round(r.total_tokens_out * m),
    run_count: Math.round(r.run_count * m),
  }
}

export function getSpendDashboard(range: SpendRange, group_by: SpendGroupBy): SpendDashboard {
  const m = RANGE_MULTIPLIER[range]
  const items = (group_by === 'agent' ? byAgentBase : byUserBase).map(r => scaleRow(r, m))
  const total_usd = Math.round(items.reduce((s, r) => s + r.total_usd, 0) * 100) / 100
  return { range, group_by, total_usd, items }
}

// Lifetime stats per agent (mock equivalent of orchestrator enrichment used by
// docs/gateway.yaml on GET /agents/{id}). Returns null for unknown agents so
// detail responses fall back gracefully when enrichment "fails".
export function getAgentStats(agentId: string): { total_spend_usd: number; runs_count: number } | null {
  const row = byAgentBase.find(r => r.id === agentId)
  if (!row) return null
  // byAgentBase numbers are 30d-scoped — we treat them as lifetime totals here
  // for demo purposes (real backend will return cumulative numbers).
  return { total_spend_usd: row.total_usd, runs_count: row.run_count }
}
